### ISSUE TITLE
Warning message Interpretation: knearneigh(x = xy, k = k) : knearneigh: identical points found

### ISSUE THREAD

**Issue by MariosBarlas** [r-spatial/spdep#11]
Hello,

I'm running spatial statistics and I get a warning that says: 

knearneigh(x = xy, k = k) : knearneigh: identical points found

Does some1 know what it means ? ( I mean mathematically where could it come from )

Thank you!

**Comment by rsbivand** [comment]
This is not an issue with the software, and should  go to [R-sig-geo](https://stat.ethz.ch/mailman/listinfo/r-sig-geo). The help page `?knearneigh` does say: 

> A warning will be given if identical points are found.

for rather obvious reasons (no two spatial observation positions may be at the same point). If you have identical observations by position, this would fail in geostatistics and point pattern analysis too. It is only a warning, so you can proceed, but the warning is to alert the user to a likely data input error.

**Comment by cypiemarrs** [comment]
How do I specify that I would like to ignore the warning? It would make sense that some points would repeat in the dataset that I am working with, yet it is keeping me from proceeding:

> Warning messages:
> 1: In knearneigh(coords, 3) : knearneigh: identical points found
> 2: In knearneigh(coords, 3) :
>   knearneigh: kd_tree not available for identical points
