### ISSUE TITLE
include.self option for mat2listw or way to specify self.included attribute on listw object

### ISSUE THREAD

**Issue by rosieluain** [r-spatial/spdep#112]
I am using the function localG_perm. I have a matrix of binary weights, based on least-cost distances between locations, so I have been using mat2listw(matrix,style="B") to generate the listw object for localG_perm. The issue I am having is that I would like to compute G*, but I have not been able to find a way to specify self.included when generating the listw from my matrix. I see that there is a way to do this when beginning with an nb object - am I missing the way to do this with a matrix? 

I attempted to get around the issue by specifying the self weights in the matrix (1s on the diagonal), but the returned vector has the attribute gstari as FALSE, so I believe the denominator in the local Getis equation would not be calculated correctly for G*. 

I also thought it might be possible to specify self.included as an attribute after the listw object was generated. Is there a way to do this? 

Thank you - any help would be much appreciated!

**Comment by rsbivand** [comment]
Not really missing a way to do  this, as self least cost distance is by definition zero, and inverse distance then +Inf. You would have first to consider what G* means for your choice of weights.

**Comment by rsbivand** [comment]
Yes, makes sense. Could you then create a toy workflow reproducing your setting? I think that after `mat2listw()`, you could extract the `"nb"`object and use `include.self()` on that, then converting back to `"listw"`.

**Comment by rosieluain** [comment]
Yes, that worked perfectly - thank you!
