### ISSUE TITLE
grDevices::hcl.colors not defined until R 3.6.0

### ISSUE THREAD

**Issue by jaganmn** [r-spatial/spdep#113]
Attempting to install `spdep` under `R < 3.6.0` gives:

```
** byte-compile and prepare package for lazy loading
Error : object 'hcl.colors' is not exported by 'namespace:grDevices'
ERROR: lazy loading failed for package 'spdep'
```

You need to conditionalize the import in `NAMESPACE`

```
if (getRversion() >= "3.6.0") {
    importFrom(grDevices, hcl.colors)
}
```

and in your code implement a fallback for `R < 3.6.0`, where `grDevices::hcl.colors` is not available.

**Comment by rsbivand** [comment]
Increased required R version to `>= 3.6.0`, any below is simply very old.

**Comment by jaganmn** [comment]
No strong reason.  `Matrix` has `Depends: R (>= 3.5)` and `Enhances: spdep`, and I was trying to run a "complete" check under R 3.5.3.  I noticed that `spdep` could not be installed and figured I'd at least report the problem.  Of course you are welcome to change to `Depends: R (>= 3.6)`, though the changes required to avoid doing so did not seem too onerous when I looked.
