### ISSUE TITLE
Typo in Global G warning

### ISSUE THREAD

**Issue by JosiahParry** [r-spatial/spdep#114]
Warning should likely say "especially" 

https://github.com/r-spatial/spdep/blob/bc2df66aa2a18f7bec2e0ce66cf94b758df3e2c0/R/globalG.R#L16

**Comment by rsbivand** [comment]
Right, will fix, thanks.

**Comment by JosiahParry** [comment]
addressed in https://github.com/r-spatial/spdep/pull/115
