### ISSUE TITLE
Clarifying Local G critical value

### ISSUE THREAD

**Issue by jordanong09** [r-spatial/spdep#117]
Hi,

Under the details section, it was stated that:
```
The critical values of the statistic under assumptions given in the references for the 95th percentile are for n=1: 1.645, n=50: 3.083, n=100: 3.289, n=1000: 3.886.
```

Can I clarify that these critical values are for the two-tailed test? This means that Z-score > 3.886 and Z-score < -3.886 is considered statistically significant for 1000 observations. Or we should divide these critical values by **2** if we are doing a two-tailed test?

**Comment by rsbivand** [comment]
Please refer to the original references (Ord & Getis 1995 p. 297, Getis & Ord 1996 p. 275). Z-scores are two-tailed by definition (they extend on both sides of 0). so you only run into the 2*pv if you go to probability values. At present Luc Anselin suggests a largest cutoff of 0.005 after FDR adjustment, a view I agree with.
