### ISSUE TITLE
minimum version of raster - conflicting methods

### ISSUE THREAD

**Issue by JosiahParry** [r-spatial/spdep#118]
Starting this week I have warnings when loading spdep 

```r
library(spdep)
#> Loading required package: sp
#> Loading required package: spData
#> To access larger datasets in this package, install the spDataLarge package with:
#> `install.packages('spDataLarge', repos='https://nowosad.github.io/drat/', type='source')`
#> Loading required package: sf
#> Linking to GEOS 3.11.0, GDAL 3.5.3, PROJ 9.1.0; sf_use_s2() is TRUE
#> Warning messages:
#> 1: multiple methods tables found for ‘direction’ 
#> 2: multiple methods tables found for ‘gridDistance’ 
```

After doing a bit of digging it looks like you've [answered this before](https://stackoverflow.com/questions/70674136/r-package-warning-multiple-methods-tables-found-for-direction). After reinstalling raster to 3.6.2 the issue disappears. 

Can we at a minimum version of terra and raster to ensure this doesn't occur?

**Comment by rsbivand** [comment]
Not here, as **spdep** does not depend on either. This is coming from **spData**. We could say spData >= 2.2.0 if need be. See also https://github.com/Nowosad/spData/issues/62 for more changes coming in **spData**.

**Comment by JosiahParry** [comment]
Absolutely makes sense!
