### ISSUE TITLE
is the number returned by poly2nb() function representing the order of the data

### ISSUE THREAD

**Issue by xu003822** [r-spatial/spdep#125]
Hi everyone,

I am using poly2nb() to find neighbors for municipalities in NJ, USA. When I used poly2nb(), it returns, for example one of the rows is:
[[1]]   integer [4]   16 143 186 426

I am wondering whether this "[[1]]" corresponds to the first observation of my dataset? and "16" corresponds to the 16th observation of the dataset.

Thanks a lot!

**Comment by rsbivand** [comment]
Please provide an example with code and do use built in data sets. It is not possible to see what you are puzzled by from this description. Did you read either vignette about nb objects?
