### ISSUE TITLE
CARBayesST

### ISSUE THREAD

**Issue by gadouaka** [r-spatial/spdep#128]
Apres avoir exécuté la commande suivante:
model2 <-CARBayesST::ST.CARar(formula = formula, family = "poisson", data = pollutionhealthdata, W=W, AR=1, burnin = 20000, n.sample = 220000, thin = 10)
le message suivant s affiche:
Summarising results.
Finished in  368.4 seconds.
Warning message:
In mat2listw(W) :
  style is M (missing); style should be set to a valid value
Que dois-je faire?

**Comment by rsbivand** [comment]
See #129
