### ISSUE TITLE
spdep and sp

### ISSUE THREAD

**Issue by ConnorDonegan** [r-spatial/spdep#134]
I am updating a package (geostan) that imports spdep and I want to make sure that I understand and respond to this warning correctly. After reading the sp evolution status updates, I was under the impression that I only needed to avoid using sp and I've been assuming that spdep will be evolving as needed. Is that right? If so, can I silence this message somehow (for geostan users)?

Thanks

```
> library(geostan)
The legacy packages maptools, rgdal, and rgeos, underpinning the sp package,
which was just loaded, will retire in October 2023.
Please refer to R-spatial evolution reports for details, especially
https://r-spatial.org/r/2023/05/15/evolution4.html.
It may be desirable to make the sf package available;
package maintainers should consider adding sf to Suggests:.
The sp package is now running under evolution status 2
     (status 2 uses the sf package in place of rgdal)
```

**Comment by rsbivand** [comment]
Wait for sp 2.1-0, coming shortly @edzer

**Comment by edzer** [comment]
2.1-0 submitted!

**Comment by ConnorDonegan** [comment]
Thanks! Glad I can keep using spdep

**Comment by rsbivand** [comment]
@ConnorDonegan Please see https://github.com/serafinialessio/mapping/issues/3#issuecomment-1689317335 for work-arounds before `sp` 2.1-1 is ready.
