### ISSUE TITLE
[Not a bug] Handling missing values in grid-based data for Geary's C

### ISSUE THREAD

**Issue by frederic-santos** [r-spatial/spdep#139]
Hi,

This issue is not a bug, rather a feature request or info request.

I would like to compute Geary's C (or Moran's I) indices of spatial autocorrelation for a set of grid-based datasets. I have a bunch of 12x3 grids such as this one:
```r
## Define a 12x3 grid:
loc <- structure(c(0.653, 1.361, 1.392, 0.991, 1.228, 3.882, 1.46, 1.056, 
1.636, 1.535, 1.578, 2.106, NA, 0.801, NA, 1.51, 1.514, 1.846, 
0.791, 1.567, 0.902, 2.011, 1.683, 1.541, 3.437, 1.095, 1.469, 
1.897, 1.866, 1.498, 1.156, 1.342, 1.809, 1.56, 1.341, 1.005), dim = c(12L, 
3L), dimnames = list(c("1", "2", "3", "4", "5", "6", "7", "8", 
"9", "10", "11", "12"), c("1", "2", "3")))

print(loc)
```

```
       1     2     3
1  0.653    NA 3.437
2  1.361 0.801 1.095
3  1.392    NA 1.469
4  0.991 1.510 1.897
5  1.228 1.514 1.866
6  3.882 1.846 1.498
7  1.460 0.791 1.156
8  1.056 1.567 1.342
9  1.636 0.902 1.809
10 1.535 2.011 1.560
11 1.578 1.683 1.341
12 2.106 1.541 1.005
```
As you can see, there may be several missing values in these grids. To the best of my knowledge, the function `geary()` does not handle missing values in such cases:

```r
library(spdep)
adj <- cell2nb(nrow = nrow(loc), ncol = ncol(loc),
               type = "queen")
ww <- nb2listw(adj, style = "B")
geary(x = as.numeric(t(loc)),
      listw = ww,
      n = length(as.numeric(loc)),
      n1 = length(as.numeric(loc)) - 1,
      S0 = Szero(ww))
```
The result we get for that is simply `NA`.

Theoretically, computing the Geary's C on the grid above is perfectly feasible, but it seems that this possibility is not implemented in `{spdep}`. What would be the fastest way to compute an index of autocorrelation for such a grid? Is this something we can pretty quickly handle on the user-side? Is there any plans to implement this kind of thing in future releases of `{spdep}`?

Thanks!

**Comment by rsbivand** [comment]
Of course, NAs are never permitted by default, as the lagged value is set to NA; the same would apply for no-neighbour observations with `zero.policy` FALSE, the default. Neither `geary` nor `geary.test` are adapted to NA values, but `moran.test` https://github.com/r-spatial/spdep/blob/46c90789e61affa495e1b9139442f4416dc7e7af/R/moran.R#L39-L45, `moran.mc` https://github.com/r-spatial/spdep/blob/46c90789e61affa495e1b9139442f4416dc7e7af/R/moran.R#L119-L126 and `moran` https://github.com/r-spatial/spdep/blob/46c90789e61affa495e1b9139442f4416dc7e7af/R/moran.R#L11 are:

```
moran(x = as.numeric(t(loc)), listw = ww,  n = length(as.numeric(loc)), S0 = Szero(ww), NAOK=TRUE)
moran.test(x = as.numeric(t(loc)), listw = ww, na.action=na.omit)
```

Here, the NA observations are omitted I can add a similar work-around to `geary` etc. if you feel it worthwhile.

**Comment by frederic-santos** [comment]
Many thanks, it's clearer now!

> Here, the NA observations are omitted. I can add a similar work-around to geary etc. if you feel it worthwhile.

It would be a useful addition to the package, if you can!

All the best,
F.

**Comment by rsbivand** [comment]
Draft additions in the `gearyNA` branch: https://github.com/r-spatial/spdep/tree/gearyNA. If you can install from github (`remotes::install_github("r-spatial/spdep@gearyNA")` or similar, you'd get:
```
> geary.test(x = as.numeric(t(loc)), listw = ww, na.action=na.omit)

	Geary C test under randomisation

data:  as.numeric(t(loc)) 
weights: ww 
omitted: 2, 8  

Geary C statistic standard deviate = 0.88858, p-value = 0.1871
alternative hypothesis: Expectation greater than statistic
sample estimates:
Geary C statistic       Expectation          Variance 
       0.83838586        1.00000000        0.03307995 
```

**Comment by rsbivand** [comment]
gearyNA branch now merged with main, default branch. Possibly built on https://r-spatial.r-universe.dev/builds.
