### ISSUE TITLE
knearneigh seg faults at k >= 999

### ISSUE THREAD

**Issue by neverfox** [r-spatial/spdep#16]
```
library(spdep)

# generate random long/lat data
coord <- cbind(runif(1000, -10.8544921875, 2.021484375), runif(1000, 49.82380908513249, 59.478568831926395))

# gives benign too many ties error
knn <- knearneigh(coord, k = 998, longlat = TRUE)

# seg faults
knn <- knearneigh(coord, k = 999, longlat = TRUE)

# give it more records, just in case that's the issue
coord <- cbind(runif(2000, -10.8544921875, 2.021484375), runif(2000, 49.82380908513249, 59.478568831926395))

# still seg faults
knn <- knearneigh(coord, k = 999, longlat = TRUE)
```

**Comment by rsbivand** [comment]
Please provide reprex (use set.seed()). This isn't a use case, as knn is only ever used for k << n. Why are you doing this? I will examine, but it is a waste of time.

**Comment by rsbivand** [comment]
The C code sets: `#define MAX_TIES 1000`, so k=999 goes through `MAX_TIES-1`, but only in the `longlat=TRUE` case. The EPS value for ties (1e-4) is large for longlat; this has now need squared for that case.

With:  611784e, resolved - please check and report back - with a convincing use case:

```
> library(spdep)
Loading required package: sp
Loading required package: Matrix
Loading required package: spData
> 
> # generate random long/lat data
> coord <- cbind(runif(1000, -10.8544921875, 2.021484375), runif(1000, 49.82380908513249, 59.478568831926395))
> 
> # gives benign too many ties error
> knn <- knearneigh(coord, k = 998, longlat = TRUE)
Error in knearneigh(coord, k = 998, longlat = TRUE) : 
  too many ties in knearneigh
In addition: Warning message:
In knearneigh(coord, k = 998, longlat = TRUE) :
  k greater than one-third of the number of data points
> 
> # seg faults
> knn <- knearneigh(coord, k = 999, longlat = TRUE)
Error in knearneigh(coord, k = 999, longlat = TRUE) : 
  too many ties in knearneigh
In addition: Warning message:
In knearneigh(coord, k = 999, longlat = TRUE) :
  k greater than one-third of the number of data points
> knn <- knearneigh(coord, k = 499, longlat = TRUE)
Warning message:
In knearneigh(coord, k = 499, longlat = TRUE) :
  k greater than one-third of the number of data points
> str(knn)
List of 5
 $ nn       : int [1:1000, 1:499] 934 175 110 109 539 180 428 651 151 792 ...
 $ np       : int 1000
 $ k        : num 499
 $ dimension: int 2
 $ x        : num [1:1000, 1:2] -7.44 -6.06 -3.48 0.84 -8.26 ...
 - attr(*, "class")= chr "knn"
 - attr(*, "call")= language knearneigh(x = coord, k = 499, longlat = TRUE)
```

**Comment by neverfox** [comment]
> Please provide reprex (use set.seed()).

Pick one. It doesn't make a difference on my system.

> This isn't a use case, as knn is only ever used for k << n. Why are you doing this?

Because I wanted you to be able to run it quickly and selected a number big enough to be valid, i.e. k < n. The actual use case involves 400,000 long/lats and k = 1000. I think that qualifies as k << n. But the point is that it doesn't matter how big I make n. I tried 10,000 random and 100,000 random with the same result.

> Please provide your real name and affiliation, I am most uncomfortable dealing with anonymous entities.

My real name is on my GitHub profile, so I'm not anonymous. I'm likewise not comfortable sharing my professional affiliations when I'm not posting this issue on behalf of any of them. In any case, that's a very odd response to someone in the open source community trying to help make your software better. Maybe GitHub isn't the platform for you.

**Comment by neverfox** [comment]
Installed the latest from master and this appears to have eliminated the seg faults. Thank you.

Now that leaves the matter of too many ties. I'm not sure how this package is calculating distance (or to what precision), but that outcome is highly specious:

```
library(spdep)
library(geosphere)

set.seed(42)

# generate random long/lat data
coord <- cbind(runif(10000, -10.8544921875, 2.021484375), runif(10000, 49.82380908513249, 59.478568831926395))

# check for unique distances using geosphere package
dists <- distm(coord)
print(length(dists[dists != 0]) / 2) # 49995000
print(length(unique(dists[dists != 0]))) # 49994999, only one tie

knn <- knearneigh(coord, k = 500, longlat = TRUE) # too many ties
```

**Comment by rsbivand** [comment]
You have still not explained why you want to find even k=1000 nearest neighbours from 400K points in a geographical coordinate reference system. If your extent is global, you need Great Circle distances (for a chosen ellipsoid and datum), if not, project and use **KNN** or **RANN**. `spdep::knearneigh()` is based by permission on  code in **class**, `class/src/class.c`. There you will also find `EPS 1e-4` and `MAX_TIES 1000`. `EPS` is used to distinguish between points that are effectively tied (too small distance to distinguish) and others with a non-zero distance. It was not written for your apparent use case.

The GC distances returned by `gcdist` are calculated using WGS84 and are in km units (the typical use case for building asymmetric lists of nearest neighbours). **geosphere** was written decades after **spdep** and for completely different purposes (software often does have a typical use case).

I imagine that you are in real estate with house prices, but do not want to project you data. I don't think many pairs of observations cross the date line, so I can't see why I should make spdep::kneighbour() do something it wasn't designed to do. Could you provide a convincing reason why I shouldn't simply ask for a well-tested PR with no regressions?

**Comment by neverfox** [comment]
> I imagine that you are in real estate with house prices

No. I'm examining fires occurring around census blocks (of which there are over 400K in the state of California). My "radius" is not based on distance but on the number of housing units (meaning distance can vary. kNN is used to limit the candidates for accumulating the HUs. 1000 was selected because there are rural cases where it takes that many "nearby" census blocks to reach the HU thresholds.

Originally, I was using Euclidean kNN (which worked well enough for an approximation) and then reshuffled on Great Earth distance once the universe was reduced. I was attempting to cut that out by directly using Great Earth distances to/from block centroids when I ran into this. If this package isn't designed for this use case, that's fine. I will either make due with the original (though someone hackish) approach or find a different solution.

**Comment by neverfox** [comment]
In short, my use case involves a need to radiate out from a point distance-wise and accumulate a metric at each point until I hit a threshold on that metric. I do not know a priori what the spatial relationship is other than the long/lat.

**Comment by rsbivand** [comment]
Good, that is much clearer. I'd suggest projecting anyway, because all operations become very much easier. You'll benefit from spatial indexing (easiest with planar coordinates) and may find two articles in the most recent R Journal helpful: https://journal.r-project.org/archive/2018/RJ-2018-025/index.html on R and PostGIS, and https://journal.r-project.org/archive/2018/RJ-2018-009/index.html on the sf package. My guess would be that indexing and querying against planar geometries in the R and PostGIS setting should be efficient; the package authors are responsive (I handled both as editor).
