### ISSUE TITLE
New vignette on subgraphs and poly2nb snap

### ISSUE THREAD

**Issue by rsbivand** [r-spatial/spdep#168]
@JosiahParry I'd be grateful for a view on https://r-spatial.github.io/spdep/articles/subgraphs.html, and agreement to use the Tokyo geometries in that vignette.

**Comment by JosiahParry** [comment]
Thanks @rsbivand! I'll give it a read. 

Let me run the data question by my colleague quickly as she provided it to me!

**Comment by rsbivand** [comment]
Thanks! I removed all the columns from the Tokyo data set apart from the ID column and the geometries, If need be, your colleague could tell us where the geometries came fropm and we could reconstruct them from that source, but maybe the divergences would vanish then.

**Comment by JosiahParry** [comment]
https://sgsup.asu.edu/sparc/multiscale-gwr

It turns out it is a test dataset from ASU’s MGWR docs

**Comment by rsbivand** [comment]
I've emailed Tomoki Nakaya to ask; `GWmodel` of which he is an author does not bundle this dataset. Maybe the gaps came from projection on a 32-bit platform - they were more common 20 years ago, and the data set was used for a 2005 Poisson GWR article.

**Comment by JosiahParry** [comment]
I forgot to give comments on this. I read it and it was very well done! 

I would only ask that you strongly emphasize

>  The ripples in one pond cannot cross into a separate pond if they are not connected.

Either bold or a block quote or something. This is the most important take away from the vignette and it is so eloquently stated. The rest is how to address or handle it using spdep.
