### ISSUE TITLE
Error: cannot allocate vector of size ... when running sacsarlm regression

### ISSUE THREAD

**Issue by giacfalk** [r-spatial/spdep#17]
I am trying to run a sacsarlm regression of a dataset of 106,000 points with one spatial weight matrix. However, I am stuck by the error Error: cannot allocate vector of size 1.7 Gb in spite of using a machine with the folllowing specifications:

8 GB RAM
i7@3.40GHz quad-core.

How can I overcome the issue?

**Comment by rsbivand** [comment]
Provide at least the verbatim code used. What setting of the `method=` argument did you use? Are your spatial weights sparse. Really this is a use issue and should go to [R-sig-geo](https://stat.ethz.ch/mailman/listinfo/r-sig-geo) where others could correct your usage.

**Comment by rsbivand** [comment]
Since Giacomo  @giacfalk has not responded, I assume that setting `method=` resolved the issue, and the problem was that the user had not read the documentation.
