### ISSUE TITLE
Data type matters in lm.LMtests and lagsarlm functions

### ISSUE THREAD

**Issue by vmoprojs** [r-spatial/spdep#19]
I did some previous treatment on my data base and had a final dataframe, say "df". It columns were computed using `tapply`. when I tried to use `lm.LMtests` or `lagsarlm` with this data I got the following error:
```
Error in matrix(0, nrow = nrow(x), ncol = ncol(x)) : 
  invalid 'ncol' value (too large or NA)
```
I tried looking for this issued with no luck. After trying different solutions, I ended up discovering that the `class` of the columns in the original data matters. X and Y internally use the function `lag.listw` and it checks for `is.vector`. So, even though my original data was a dataframe, column classes matter. So I made sure that each column was `numeric` type and then everything worked. 

When I had the problem, `str` function reported: `num [1:24(1d)]`, and the problem was solved when str reported just `num`.

Hope this helps

**Comment by rsbivand** [comment]
Do not use issues for users confusion. Do subscribe to R-sig-geo and post there, always with a reproducible example using built in data. You have not shown any of your workflow, including how you actually constructed (aggregated?) your df (see `?tapply`):

```
> o <- tapply(warpbreaks$breaks, warpbreaks[, 3, drop = FALSE], sum)
> str(o)
 num [1:3(1d)] 655 475 390
 - attr(*, "dimnames")=List of 1
  ..$ tension: chr [1:3] "L" "M" "H"
> o <- c(tapply(warpbreaks$breaks, warpbreaks[, 3, drop = FALSE], sum))
> str(o)
 Named num [1:3] 655 475 390
 - attr(*, "names")= chr [1:3] "L" "M" "H"
> o <- aggregate(warpbreaks$breaks, warpbreaks[, 3, drop = FALSE], sum)
> str(o)
'data.frame':	3 obs. of  2 variables:
 $ tension: Factor w/ 3 levels "L","M","H": 1 2 3
 $ x      : num  655 475 390
```

**Comment by rsbivand** [comment]
My reprex:

```
library(spdep)
data(nc.sids)
o <- tapply(nc.sids$SID74, nc.sids$CNTY.ID, sum)
str(o)
lagsarlm(o ~ 1, listw=nb2listw(ncCR85.nb))
lagsarlm(c(o) ~ 1, listw=nb2listw(ncCR85.nb))
```

**Comment by rsbivand** [comment]
Commit https://github.com/r-spatial/spdep/commit/7b88ca97cdb1ea40352aa6589ac475b4e25555cb should fix issue.
