### ISSUE TITLE
cell2nb arguments

### ISSUE THREAD

**Issue by ChimskyChim** [r-spatial/spdep#20]
It appears that the argument 'ncol' in the cell2nb() actually references the number of rows and the argument 'nrow' actually references the number of columns.  Here is an example of the potential problem:

t.nb <- cell2nb(nrow=50,ncol=10,type='rook',torus=FALSE)
head(t.nb)

Note that the neighbors of cell 1 are cell 2 (correct) and cell 51 (incorrect)

**Comment by rsbivand** [comment]
Now, with legacy= added:

```
GT <- GridTopology(c(1, 1), c(1,1), c(10, 50))
SPix <- as(SpatialGrid(GT), "SpatialPixels")
nb_rook_cont <- poly2nb(as(SPix, "SpatialPolygons"), queen=FALSE)
nb_rook_dist <- dnearneigh(coordinates(SPix), 0, 1.01)
all.equal(nb_rook_cont, nb_rook_dist, check.attributes=FALSE)
## [1] TRUE
t.nb <- cell2nb(nrow=50, ncol=10, type='rook', legacy=TRUE)
isTRUE(all.equal(nb_rook_cont, t.nb, check.attributes=FALSE))
## [1] FALSE
t.nb <- cell2nb(nrow=50, ncol=10, type='rook')
isTRUE(all.equal(nb_rook_cont, t.nb, check.attributes=FALSE))
## [1] TRUE
```
I think https://github.com/r-spatial/spdep/commit/732b09cf87813e5039dc444cce508f0990de4f3b fixes the issue - if you can install from github, could you please check?

**Comment by ChimskyChim** [comment]
I just updated some of my libraries as well as the changes you made.  I just did a quick test and it seems to be corrected...thanks!
