### ISSUE TITLE
Update Rnws and/or add vignettes, articles

### ISSUE THREAD

**Issue by angela-li** [r-spatial/spdep#25]
As mentioned in the website issue (#23), @edzer and I noticed that the SIDS and spatial filtering vignettes were Rnws, which we could change over to Rmds. I suggested maybe the thing to do would be to break them up into articles for the website. @rsbivand even suggested adding a new vignette or two, regarding methods for ML fitting.

Thoughts on what makes sense? I think it could also be useful to add an article/vignette called "Quickstart" walking through performing spatial analysis on one specific example, highlighting a few key `spdep` functions.

**Comment by rsbivand** [comment]
OK, if Quickstart, should we start quickly with testing for spatial autocorrelation (with the McMillen 2003 teaser of finding spatial autocorrelation where there is none), or rather ML model fitting? GM model fitting is in **sphet**, really ...

**Comment by edzer** [comment]
Sounds good; I would extend that (maybe in a second vignette?) with some simple spatial smoothing examples, and a spatial regression model (SAR and CAR) with spatial neighbours / weights.

**Comment by angela-li** [comment]
Getting started converting the SIDS Rnw to Rmd - @rsbivand do you happen to have a .bib version of the references included in the vignette? Will make it easier to do the references in RMarkdown

**Comment by rsbivand** [comment]
No .bib file; when the vignette was written, there were no automatic facilities for running bibtex for building the output PDF - there are now through `tools::texi2pdf()`.  I'll try to create an (updated) .bib file.

**Comment by rsbivand** [comment]
Created refs.bib here:
[refs.zip](https://github.com/r-spatial/spdep/files/2736401/refs.zip)

Currently missing DOIs and anselin+syabri+smirnov:2002 (on a meeting CDROM, probably not online?).

Suggest using the same bib file for all Rnw -> Rmd conversions - where to put it?

**Comment by angela-li** [comment]
Thank you Roger! This is exactly what I needed. I agree that using the same .bib file for `sids.Rmd`, `CO69.Rmd`, and `SpatialFiltering.Rmd` is a good idea - would it be possible for you to add the citations from the other two Rnw vignettes to `refs.bib`? I can do my best to add DOIs if you think they're valuable (I remember the original didn't have them?).

Once we have that, we can include `refs.bib` in the `vignettes/` folder, then reference it from the YAML header in each Rmd (`bibliography: refs.bib`) to generate the citations!

**Comment by rsbivand** [comment]
No, DOI didn't exist, but now could be url = {https://doi.org/...} giving direct links. I'll try to add the other references.

**Comment by edzer** [comment]
Only giving the doi as doi = { ... }, i.e. without the https://doi.org/ prefix and omitting the url = { } generates the said link and only shows the DOI.

**Comment by rsbivand** [comment]
OK, the opposite of JSS and RJ (where we convert doi= to url= before building the PDF).

**Comment by rsbivand** [comment]
Here with all the references except the Anselin one from sids. @angela-li could you please try to see if multilisa.pdf is online anywhere. 

[refs.zip](https://github.com/r-spatial/spdep/files/2738110/refs.zip)

I'm unsure whether I should add the file prior to your PR - could you add it in your PR? Then we can look at using **sf** and getting it from the canonical **spData** if that is the most complete version.
