### ISSUE TITLE
Cholmod error in ME function

### ISSUE THREAD

**Issue by sigmafelix** [r-spatial/spdep#28]
First of all, I appreciate all contributors and authors of `spdep` package. 

I currently conduct a Moran eigenvector spatial filtering analysis using datasets on [GeoDa Center](https://geodacenter.github.io) for a study. Among datasets, there is an issue when applying `ME` function to New York City datasets; it throws an identical error of `Error in sW %*% var :  Cholmod error 'X and/or Y have wrong dimensions' at file ../MatrixOps/cholmod_sdmult.c, line 90`. I guess the reason of the error is that there are several distant islands in New York City, wherein produces some problems I cannot specify when `spdep` package translates spatial neighbors to `listw` or derived `matrix` object. For a reference, there was no such error when applying `ME` function to data from other regions.

I hope that this is just a data problem.

Here is a reproducible code chunk:
```{r}
## problem - reproducible code
library(spdep)
library(rgdal)

replace_na2 <- function(x) ifelse(is.na(x), 0, x)

download.file('https://s3.amazonaws.com/geoda/data/nyc_2000Census.zip', 
              destfile = 'D:/nyc_2000Census.zip') # might require a user to modify a directory to decompress
dir.create('D:/temp')
unzip('D:/nyc_2000Census.zip', exdir = 'D:/temp')

nye <- rgdal::readOGR(dsn = 'D:/temp/NYC_2000Census.shp', layer = 'NYC_2000Census')
nye <- spTransform(nye, CRS('+init=epsg:3857'))

nye$hs_d <- nye$hs / nye$over25 * 1000
nye$somecol_d = nye$somecol / nye$over25 * 1000
nye$col_d = nye$college / nye$over25 * 1000
nye$master_d = nye$master / nye$over25 * 1000
nye$prof_d = nye$prof / nye$over25 * 1000
nye$phd_d = nye$phd / nye$over25 * 1000

for (i in 57:62){
  nye@data[,i] <- ifelse(is.na(nye@data[,i]), 0, nye@data[,i])
}

nyet <- split(nye, nye@data$BoroName)
nyet.nb <- lapply(nyet, function(x) poly2nb(x))
nyet.listw <- lapply(nyet.nb, function(x) nb2listw(x, zero.policy = TRUE))

nyet.xlist <- c('GENDER_PAR', 'PER_PRV_SC', 'YOUTH_DROP', 
                'PER_MNRTY', 'mean_inc', 'HS_DROP', 'PER_ASIAN')
nyet.ylist <- c('hs_d', 'somecol_d', 'col_d', 'master_d', 
                'prof_d', 'phd_d', 'COL_DEGREE')

nyet.forms <- split(nyet.ylist, nyet.ylist) 
nyet.forms <- lapply(nyet.forms, function(x) as.formula(paste(x, '~', paste(nyet.xlist, collapse = '+'))))

# Gaussian linear regression: no error
nyet.lm1 <- lapply(nyet.forms, function(x) lm(formula = x, data = nyet[[1]]@data))

# Moran Eigenvector GLM filtering: produces an error
nyet.me1 <- lapply(nyet.forms,
                   function(x) ME(formula = x, data = nyet[[1]]@data, 
                                  stdev = TRUE, listw = nyts.listw[[1]]))
# Error in sW %*% var : 
# Cholmod error 'X and/or Y have wrong dimensions' at file ../MatrixOps/cholmod_sdmult.c, line 90
```

**Comment by rsbivand** [comment]
Please re-write the reprex without %>% and tidyverse (mutate, etc. are often the source of trouble). I'll look at it once it is in regular base R.

**Comment by sigmafelix** [comment]
Thank you for rapid response. I have modified the code above. I also have modified `sf`-related codes to avoid possible errors.

**Comment by rsbivand** [comment]
Your script doesn't replicate for me:

```
> nyet.me1 <- lapply(nyet.forms,
+                    function(x) ME(formula = x, data = nyet[[1]]@data, 
+                                   stdev = TRUE, listw = nyet.listw[[1]]))
Error in ME(formula = x, data = nyet[[1]]@data, stdev = TRUE, listw = nyet.listw[[1]]) : 
  base correlation larger than alpha
```

which is a valid error message. Please post a script that only runs one `ME()` call on a formula that generates your error.

**Comment by rsbivand** [comment]
The error applies to formulae 3 and 7, 1:2 and 4:6 are OK. Why are you using `ME()`? Isn't `SpatialFiltering()` more reasonable anyway? What are you trying to do? Fit various models by borough with the same X variables to self-constructed rates? Should you be using Poisson regression (or NB regression) on counts, offsetting by log population. This doesn't make much sense, but if you can provide a simple example that reproduces the error, I'll try to see what it is. It looks as though you have mixed up objects and are trying to operate on non-conformant matrices.

**Comment by sigmafelix** [comment]
Thank you for the kind response. I prefer the `ME()` function because my study is in line with studies employing Principal Coordinates of Neighborhood Matrix which is common in the literature I considered to cite in our study. I should take much effort on the model specification as you have kindly suggested.

After the re-examination, I became known that the error I specified is not produced when I replace `NaN` and `NA` values to `0`. The issue of non-comformant matrix (`Cholmod ...`) may be attributed to the presence of `NA` or `NaN` values in the source `data.frame`. I would suggest to add a warning message on data check or new `na.action`  argument for `data`  in `SpatialFiltering()` and `ME()` functions. I guess that two functions might remove rows with at least a `NA` value from `data.frame` before fitting the main eigenvector analysis internally.

**Comment by rsbivand** [comment]
`na.action` added to `ME()` and `SpatialFiltering` per https://github.com/r-spatial/spdep/commit/51c6e947529b1c69b36c1392442a5282fc567b9e
