### ISSUE TITLE
Split model fitting functions out into new package

### ISSUE THREAD

**Issue by rsbivand** [r-spatial/spdep#31]
I'm surveying the reverse dependencies of **spdep** https://github.com/r-spatial/spdep and see that most packages using functions from **spdep** either just construct neighbour objects, or in a few cases also use tests for spatial dependence. A small cluster of packages use model fitting functions. 

To make maintenance simpler, I'm considering splitting the model fitting functions out into a new package, probably to be called **spreg** (@gpiras). I'd welcome reactions.

**Comment by edzer** [comment]
will the other package get the name `spdep`, or will you keep an un-maintained `spdep` legacy package?

**Comment by rsbivand** [comment]
No, **spdep** will have the neighbour generating functions and tests for spatial autocorrelation, so most users will see no change. The model fitting functions will move to **spreg**  and be set deprecated in **spdep** but pass through to **spreg** (circular dependency **spdep** <-> **spreg**) with a dated cut off. After the cut off, deprecated will go defunct, and **spdep** will no longer depend on **spreg**, but **spreg** will continue to depend on **spdep**. Does that seem sensible?

**Comment by edzer** [comment]
Yes!

**Comment by rsbivand** [comment]
Think **spdep** -> ch 17, **spreg** -> ch 18 (https://keen-swartz-3146c4.netlify.com/).

**Comment by angela-li** [comment]
I think this is a great idea! There's so much currently in spdep, and splitting it out into two packages would make it easier for researchers to understand and use the specific functionalities in each. Great plan!

**Comment by dylanbeaudette** [comment]
Excellent. Thanks Roger for you work and long-term commitment to the cause.

**Comment by gpiras** [comment]
Hi Roger:

I think it would make sense. Maybe we can have a chat to figure out the details…

Best,
G.

**Comment by rsbivand** [comment]
Big road bump - the name **sprep** is lost, as **SPreg** https://cran.r-project.org/package=SPreg was published March 16. @angela-li @gpiras what other name? **spmodels** is vacant, but I need a very quick resolution

**Comment by edzer** [comment]
Any reason to keep the `sp` prefix? I suggested `arealdatamodels` on twitter.

**Comment by rsbivand** [comment]
**arealdatamodels** is too long, **spreg** is used in Python and Stata, we were too late in staking turf. The **sp** prefix isn't the **sp** package, **spdep** pre-dated **sp**. In the same area are **sphet** and **splm** (the latter really **s**-**plm**).

**Comment by edzer** [comment]
Too long for who? I pondered about `arealunitsdatamodels` :-) At least it's descriptive.

**Comment by rsbivand** [comment]
Maybe **spW** because all the models use **W**?

**Comment by gpiras** [comment]
Spregress?

**Comment by rsbivand** [comment]
Also on https://twitter.com/RogerBivand/status/1109041845227663360

**Comment by gpiras** [comment]
I also like spmodel o the short version spmod

**Comment by rsbivand** [comment]
By the way, **specon** and **spatecon** are also free, playing to spatial econometrics ...

**Comment by rsbivand** [comment]
New thread; need git/github help. The current **spreg** is at https://github.com/rsbivand/spreg, and I'll choose a new name shortly. Once the new name is substituted in the split-out package and **spdep**, I'd like to add Travis to the split-out package (should be OK), but also to create a remote branch on r-spatial/spdep matching my local branch:

```$ git status
On branch split_spreg
nothing to commit, working tree clean
```
and set up a Travis from this spdep branch running against the github repo of the split-out package.

How should I:

1) set up regular Travis on the spreg/new-name repo 
2) push my local branch with the out-split **spdep** unmerged
3) set up Travis on the out-split **spdep** branch using the spreg/new-name repo
4) on stabilisation, merge **spdep** branch with master

Locally, the **spdep** out-split branch completes check OK on the spreg/new-name package, and the spreg/new-name package itself completes check OK (apart from needing a new name).

I'm looking to submit spreg/new-name to CRAN soon, then run the rev-dep checks and inform affected maintainers before submitting the out-split **spdep** to CRAN. 

I'll look at conflict masking on R 3.6 for the book chapter until deprecated -> defunct.

**Comment by edzer** [comment]
I do this so infrequently that explaining how to set up travis would take me considerably more time than actually doing it. I suggest you transfer the repo to r-spatial organisation, then I'll be happy to do it. Travis should be a convenience, not a burden.

Travis works always on commits to all branches: click the travis badge, and on travis click the "branches" tab.

**Comment by rsbivand** [comment]
split_spreg branch pushed; split-out package names **spatialreg**.

How can I move that package to r-spatial from rsbivand? Try to start a repo r-spatial/spatialreg and manually copy raw files exported from git? Or is there a better way?

**Comment by edzer** [comment]
Goto repo; Settings -> Transfer ownership

**Comment by rsbivand** [comment]
Thanks, done - how now to change its name spreg -> spatialreg? I don't see a "settings" icon ...

**Comment by rsbivand** [comment]
OK, thanks, saw it change when refreshing tab.

**Comment by edzer** [comment]
Note that the repo is still a fork, and not a repo you created. I don't know whether this matters.

**Comment by edzer** [comment]
Settings -> danger zone points to [this](https://help.github.com/en/articles/duplicating-a-repository) for un-forking (duplicating) a repo.

**Comment by rsbivand** [comment]
I'll think about it, maybe it should be done, as gpiras/spreg has effectively nothing in it.

**Comment by rsbivand** [comment]
I've made a PR on gpiras/spreg from here. Do you know if forks are symmetric, so that he could make a PR on this repo from his? If not, we might try to unfork, but that looks like messing up repo names.

**Comment by rsbivand** [comment]
They are not symmetric, the base is appears to be gpiras/spreg,

**Comment by rsbivand** [comment]
OK - @edzer please change the name of spatialreg to something else (I don't have access to settings), and I'll change the un-forked spatialreg1 to spatialreg once the name is free in r-spatial.

**Comment by edzer** [comment]
[done](https://github.com/r-spatial/spatialreg_moved)

**Comment by rsbivand** [comment]
**spatialreg** submitted to CRAN, r-spatial/asdar-book.org modified code in 1ed/lat2 and 2ed/lat updated to use **spatialreg** (and so run my nightly checks).

**Comment by edzer** [comment]
Great, that was fast!

**Comment by rsbivand** [comment]
**spdep** 1.1-2 on its way to CRAN, the deprecated logic needed unpicking to allow reverse dependencies to check cleanly without **spatialreg** installed, so there are lots of namespace conflicts, so attach **spatialreg** after **spdep** to get the **spatialreg** versions of model fitting functions.

**Comment by rsbivand** [comment]
Announcement:

https://stat.ethz.ch/pipermail/r-sig-geo/2019-April/027230.html

I am sorry to have to disturb users of the spdep package who have used it to
fit spatial regression models.

The package has become large and hard to maintain. Functions to create and
handle spatial neighbours, and to test for spatial autocorrelation remain in
spdep. Functions to fit spatial regression models are now in the new package
spatialreg (1.1-3 on CRAN). They are _also_ in spdep 1.1-2 now on its way to
CRAN.

If you use spdep as you have done until now, the versions of the functions
in spdep will be used if you have not installed spatialreg, and you will see
warnings that the spdep functions are deprecated. If you have installed
spatialreg, you will see warnings too, but the estimation will be done using
the spatialreg namespace internally. If you install spatialreg, and attach
spdep followed by spatialreg, you will see that the spdep model fitting
functions are masked by their equivalents in spatialreg.

During May, I expect to make the spdep versions of the model fitting
functions defunct, gradually removing the masking problem. Most use of spdep
by packages importing its namespace or attaching it only use functions
creating and handling neighbour objects. The division of functionalities
will benefit that majority of packages, because spdep will load faster and
draw in fewer packages on which it depends. However, improving workflows for
users of those packages means that users of model fitting functions will
need to use spdep for neighbour objects and in addition spatialreg for model
estimation and evaluation.

This split was discussed on github:

https://github.com/r-spatial/spdep/issues/31

and twitter: https://twitter.com/RogerBivand/status/1105023658341351424

Please take up issues on github:

https://github.com/r-spatial/spdep/issues
https://github.com/r-spatial/spatialreg/issues

on the list or by direct email.

I hope that this reconfiguration will improve the software going forward.

Linked **spatialreg** issue: https://github.com/r-spatial/spatialreg/issues/2
