### ISSUE TITLE
Interpretation issues. 

### ISSUE THREAD

**Issue by kiaralherpiniere** [r-spatial/spdep#33]
Hi, 
I have run a Moran I test on the residuals of my model using spdep. 
I am unsure if I understand correctly how to interpret this, or if I have made a mistake.
Can you help me understand please? 
```
mod11<-lm(B2.av ~ LAI * solar + Nest.type ,data=FINAL)
Mac<-moran.test(residuals(mod11), listw=nb2listw(nlist, style="W"))
```
Output:
```
Moran I test under randomisation

data:  residuals(mod11)  
weights: nb2listw(nlist, style = "W")    

Moran I statistic standard deviate = -43.983, p-value = 1
alternative hypothesis: greater
sample estimates:
Moran I statistic       Expectation          Variance 
    -1.405532e-02     -2.458331e-05      1.017617e-07 
```
Does this suggest that my Moran I is  -1.405532e-02, which would show no spatial autocorrelation? Or have I got that completely wrong?

Thank you

**Comment by rsbivand** [comment]
Yes, completely wrong. Never use `moran.test()` wit regression residuals, only use `lm.morantest()` or its saddlepoint approximation or exact derivative. Only examine the standard deviate - the actual value of Moran's I is not what you should interpret. You seem to have large N, and probably have an unsuitable weights object.

Do not ask for help via issues, subscribe to R-sig-geo at https://stat.ethz.ch/mailman/listinfo/r-sig-geo and ask there.
