### ISSUE TITLE
subset.nb fails when "names" attribute is set

### ISSUE THREAD

**Issue by matmo** [r-spatial/spdep#34]
If I am trying to subset a nb object that has an attribute "names" the subsetting fails:

```{r}
> subset(nb, !is.na(gini))
Error in attr(z, xattrs[i]) <- attr(x, xattrs[i]) :
  'names' attribute [73056] must be the same length as the vector [64689]
```
(73056-64689) being the difference between the original neighbour list and the subsetted one.

The error seems to be caused by rows 32ff in `R/subset.nb.R`:
```{r}
    for (i in 1:length(xattrs)) {
	if (xattrs[i] != "region.id")
	    attr(z, xattrs[i]) <- attr(x, xattrs[i])
    }
```
If I understand correctly, the original xattrs (from x) are copied back to the subsetted nb (z), one of these is the vector of IDs `names`. The names are initialized in z as numbers `1:n` and then overwritten, in this case with `attr(x, "names")` which however includes all IDs and not only those of the subset. It is therefore larger and not of "same length", hence the error.

**Comment by matmo** [comment]
Sorry, this seems to be an artifact of a broken nb object -

**Comment by rsbivand** [comment]
OK, if you have a small reprex, I could try to make the error messages more helpful.
