### ISSUE TITLE
The new Durbin= argument possible issue

### ISSUE THREAD

**Issue by omm718** [r-spatial/spdep#37]
Hello,

About the Durbin= argument which has been recently modified:
I'm getting an error only when using this argument to subset the RHS variables.
Is it possible to get the error "Input data and neighbourhood list have different dimensions" in the Create_WX step when the # of rows in the spatial data frame and the length of lists neighbours are in fact equal? 
As per before, it was Durbin = ~ X. What's the most recent formula interface that subsets the RHS variables to be lagged as mentioned in one of the prior issues?

I don't know if the issue I'm facing is because of the updates on the argument. Looking at the source code, I shouldn't be getting this error. Any thought would be truly appreciated.

Omid

**Comment by rsbivand** [comment]
Thanks for raising this. I've moved it to **spatialreg** as https://github.com/r-spatial/spatialreg/issues/10, please follow up there, as the affected functions are in **spatialreg** and are deprecated in **spdep**. My response there: without a fully reproducible example preferably using a built-in data set, nobody can offer any advice.
