### ISSUE TITLE
k-nearest neighbours from distance matrix in spdep (knn in 3D distances)

### ISSUE THREAD

**Issue by pollicipes** [r-spatial/spdep#38]
Dear all,   
I am using the `spdep` package to compute Local Moran Index (LMI).  My problem is that I am using 3D coordinates (x,y,z), and I would like to compute the k-nearest neighbours (k=10) for each point in my 3D space. I have already done this in 2D, by doing the following:    
```
library(spdep)
set.seed(11)
x=runif(100, -1, 1)
y=runif(100, -1, 1)
full=data.frame(x,y)
neighs_k <- knn2nb(knearneigh(as.matrix(full), k = 10))  
neighs_mat_k <- nb2listw(neighs_k, style = "W",zero.policy=TRUE)  
```
And then I can easily proceed using the `neighs_mat_k object`.  However, when using x,y,z (3D data) coordinates I can't run the `knearneigh()` function on it. I tried converting my data to a distance matrix and using `mat2listw()` function like this:  

```
D <- as.matrix(dist(full, diag=FALSE, upper=FALSE)) 
test1 <- mat2listw(D)  

```
...but now I don't know how to retrieve the k-nearest weights from my test1 object (which would correspond to k-nearest neighbours) without changing the class of test1, which is:  

```
class(test1) 
# [1] "listw" "nb" 
# and contains...: 
ls(test1)   
# [1] "neighbours" "style"      "weights"  
```
Thus, if I change the class of test1 to a a regular list with the top 10 smallest weights for each point (corresponding to the 10 smallest distances to points), then the following steps to calculate LMI will not work, because its required that the object is a `listw()` class.  

How should I do this? Is this even the right way to proceed? Would it be possible for the function to accept the coordinates x,y,z (3D) ? 

Thanks in advance!

**Comment by rsbivand** [comment]
Please try this out if you can install from source: `remotes::install_github("r-spatial/spdep")`. If you use Windows, I can run up a Windows binary when the winbuilder service is up again after the weekend.

**Comment by pollicipes** [comment]
Thanks for looking at this, Roger.
Will try it soon. I’m running Linux, so its ok.

Best,
Juan


El 15 feb 2020, a las 17:13, Roger Bivand <notifications@github.com> escribió:

﻿

Please try this out if you can install from source: remotes::install_github("r-spatial/spdep"). If you use Windows, I can run up a Windows binary when the winbuilder service is up again after the weekend.

**Comment by karimhalaseh** [comment]
Hello,

Wasn't sure whether to open a new issue for this since it seems very related, but would it be possible to update dnearneigh to accommodate 3d data as well?

Thanks!

**Comment by rsbivand** [comment]
A new issue, please.
