### ISSUE TITLE
row.names in poly2nb works only for sp, not sf?

### ISSUE THREAD

**Issue by MatthieuStigler** [r-spatial/spdep#39]
Hi Roger! Hope you are doing well!?

It looks like the `row.names` argument is passing the attributes *region.id* only if the object is `SpatialPolygons` style, but not from `sf/sfc`? See below. 

Thanks!

``` r
library(spdep)
#> Loading required package: sp
#> Loading required package: spData
#> To access larger datasets in this package, install the spDataLarge
#> package with: `install.packages('spDataLarge',
#> repos='https://nowosad.github.io/drat/', type='source')`
#> Loading required package: sf
#> Linking to GEOS 3.8.0, GDAL 3.0.4, PROJ 7.0.0
library(sf)
library(dplyr)
packageVersion("spdep")
#> [1] '1.1.3'


columbus <- st_read(system.file("shapes/columbus.shp", package="spData")[1], quiet=TRUE) %>% 
  mutate(id_name = apply(t(combn(letters, 2)), 1, paste, collapse = "")[1:n()])

poly2nb(as(columbus, "Spatial"), row.names = columbus$id_name) %>% 
  attr("region.id")
#>  [1] "ab" "ac" "ad" "ae" "af" "ag" "ah" "ai" "aj" "ak" "al" "am" "an" "ao" "ap"
#> [16] "aq" "ar" "as" "at" "au" "av" "aw" "ax" "ay" "az" "bc" "bd" "be" "bf" "bg"
#> [31] "bh" "bi" "bj" "bk" "bl" "bm" "bn" "bo" "bp" "bq" "br" "bs" "bt" "bu" "bv"
#> [46] "bw" "bx" "by" "bz"
poly2nb(columbus, row.names = columbus$id_name) %>% 
  attr("region.id")
#>  [1] "1"  "2"  "3"  "4"  "5"  "6"  "7"  "8"  "9"  "10" "11" "12" "13" "14" "15"
#> [16] "16" "17" "18" "19" "20" "21" "22" "23" "24" "25" "26" "27" "28" "29" "30"
#> [31] "31" "32" "33" "34" "35" "36" "37" "38" "39" "40" "41" "42" "43" "44" "45"
#> [46] "46" "47" "48" "49"
```

<sup>Created on 2020-04-12 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by rsbivand** [comment]
Please do not use non-base (i.e. tidyverse) in reprex for me. Note that
tidyverse rejects row.names in general, so they cannot be relied on being
present, I think. I'll look when time permits.

Roger Bivand
Falsensvei 32
5063 Bergen

man. 13. apr. 2020, 06.22 skrev Matthieu <notifications@github.com>:

**Comment by edzer** [comment]
When the first argument is of class `sf`, `poly2nb` takes the row.names of that, ignoring the `row.names` argument. Try
```r
row.names(columbus) = columbus$id_name
poly2nb(columbus) %>% attr("region.id")
```
Looks like this is not yet documented.

**Comment by rsbivand** [comment]
`?poly2nb`

> row.names: character vector of region ids to be added to the neighbours
          list as attribute ‘region.id’, default ‘seq(1, nrow(x))’; if
          ‘polys’ has a ‘region.id’ attribute, it is copied to the
          neighbours list.

Has been like this for 18+ years, before **sp**. Documentation now edited.

**Comment by MatthieuStigler** [comment]
I am sorry, I am still confused about this. I feel there is still a different way to handle this between sp and sf? The comparison seems also complicated by the fact that `as(sf, "Spatial")` does not seem to preserve attributes?

- **sp**: use argument `row.names`. If NULL use attribute `region.id`. If NULL set default 1:...
- **sf**: Use attribute `region.id`. If NULL set default 1:... Never use argument `row.names`

Is this correct? Assuming this not very consitent status quo is deemed to be the ideal situation, would this description be more fair?

_row.names: character vector of region ids to be added to the neighbours list as attribute ‘region.id’, default ‘seq(1, nrow(x))’; if NULL and ‘polys’ has a ‘region.id’ attribute, this attribute is copied to the neighbours list. If the object derives from sf, this argument is never used, it will return use instead the attribute ‘region.id’ if existing, or the default ‘seq(1, nrow(x))’_ 

Code without tidyverse :-) 

``` r
library(spdep)
#> Loading required package: sp
#> Loading required package: spData
#> To access larger datasets in this package, install the spDataLarge
#> package with: `install.packages('spDataLarge',
#> repos='https://nowosad.github.io/drat/', type='source')`
#> Loading required package: sf
#> Linking to GEOS 3.8.0, GDAL 3.0.4, PROJ 7.0.0
library(sf)
packageVersion("spdep")
#> [1] '1.1.3'

columbus <- st_read(system.file("shapes/columbus.shp", package="spData")[1], quiet=TRUE) 
columbus$id_name <- apply(t(combn(letters, 2)), 1, paste, collapse = "")[1:nrow(columbus)]

attr(columbus, "region.id")
#> NULL

columbus_rowname <- columbus
rownames(columbus_rowname) <-  columbus$id_name
attr(columbus_rowname, "region.id") <- columbus$id_name

columbus_rowname_sp <- as(columbus_rowname, "Spatial")
attr(columbus_rowname_sp, "region.id")
#> NULL
attr(columbus_rowname_sp, "region.id") <- columbus$id_name



## object has no explicit region.id attribute
attr(poly2nb(as(columbus, "Spatial"), row.names = columbus$id_name),  "region.id")
#>  [1] "ab" "ac" "ad" "ae" "af" "ag" "ah" "ai" "aj" "ak" "al" "am" "an" "ao" "ap"
#> [16] "aq" "ar" "as" "at" "au" "av" "aw" "ax" "ay" "az" "bc" "bd" "be" "bf" "bg"
#> [31] "bh" "bi" "bj" "bk" "bl" "bm" "bn" "bo" "bp" "bq" "br" "bs" "bt" "bu" "bv"
#> [46] "bw" "bx" "by" "bz"
attr(poly2nb(columbus, row.names = columbus$id_name),  "region.id")
#>  [1] "1"  "2"  "3"  "4"  "5"  "6"  "7"  "8"  "9"  "10" "11" "12" "13" "14" "15"
#> [16] "16" "17" "18" "19" "20" "21" "22" "23" "24" "25" "26" "27" "28" "29" "30"
#> [31] "31" "32" "33" "34" "35" "36" "37" "38" "39" "40" "41" "42" "43" "44" "45"
#> [46] "46" "47" "48" "49"

# object has explicit region.id attribute 
attr(poly2nb(columbus_rowname_sp, row.names = rev(columbus$id_name)),  "region.id")
#>  [1] "bz" "by" "bx" "bw" "bv" "bu" "bt" "bs" "br" "bq" "bp" "bo" "bn" "bm" "bl"
#> [16] "bk" "bj" "bi" "bh" "bg" "bf" "be" "bd" "bc" "az" "ay" "ax" "aw" "av" "au"
#> [31] "at" "as" "ar" "aq" "ap" "ao" "an" "am" "al" "ak" "aj" "ai" "ah" "ag" "af"
#> [46] "ae" "ad" "ac" "ab"
attr(poly2nb(columbus_rowname, row.names = rev(columbus$id_name)),  "region.id")
#>  [1] "ab" "ac" "ad" "ae" "af" "ag" "ah" "ai" "aj" "ak" "al" "am" "an" "ao" "ap"
#> [16] "aq" "ar" "as" "at" "au" "av" "aw" "ax" "ay" "az" "bc" "bd" "be" "bf" "bg"
#> [31] "bh" "bi" "bj" "bk" "bl" "bm" "bn" "bo" "bp" "bq" "br" "bs" "bt" "bu" "bv"
#> [46] "bw" "bx" "by" "bz"

## use does not specify row.names
attr(poly2nb(columbus_rowname_sp),  "region.id")
#>  [1] "ab" "ac" "ad" "ae" "af" "ag" "ah" "ai" "aj" "ak" "al" "am" "an" "ao" "ap"
#> [16] "aq" "ar" "as" "at" "au" "av" "aw" "ax" "ay" "az" "bc" "bd" "be" "bf" "bg"
#> [31] "bh" "bi" "bj" "bk" "bl" "bm" "bn" "bo" "bp" "bq" "br" "bs" "bt" "bu" "bv"
#> [46] "bw" "bx" "by" "bz"
attr(poly2nb(columbus_rowname),  "region.id")
#>  [1] "ab" "ac" "ad" "ae" "af" "ag" "ah" "ai" "aj" "ak" "al" "am" "an" "ao" "ap"
#> [16] "aq" "ar" "as" "at" "au" "av" "aw" "ax" "ay" "az" "bc" "bd" "be" "bf" "bg"
#> [31] "bh" "bi" "bj" "bk" "bl" "bm" "bn" "bo" "bp" "bq" "br" "bs" "bt" "bu" "bv"
#> [46] "bw" "bx" "by" "bz"
```

<sup>Created on 2020-04-13 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by rsbivand** [comment]
Please motivate your issue. Why do you need to use this optional part of nb
pbjects? Why is using the region.id= argument not an adequate resolution?
Why do you need this set under your control but not using the argument
provided?

Roger Bivand
Falsensvei 32
5063 Bergen

man. 13. apr. 2020, 19.51 skrev Matthieu <notifications@github.com>:

**Comment by MatthieuStigler** [comment]
Hi Roger

Sorry if you feel I am being finicky on that, that's not my intention!

My workflow is that I am using `attr(poly2nb(.),  "region.id")` in a later call, so happy to have that attribute present. And arguably, I can totally have a sf/sp dependent workflow, using the function `poly2nb` differently depending on whether the input is sf or sp. I was arguing mainly for the sake of (aesthetic) consistency, so feel free to discard that argument. But do you see inaccuracies with the description of the argument I suggest?

Thanks!

**Comment by rsbivand** [comment]
Why is your workflow using `attr(poly2nb(.), "region.id")`? 

The underlying reason for the `"region.id"` was to permit tests for spatial autocorrelation to check that the names of a named numeric vector of values to be tested were in the same order as the spatial weights used, as described in `?chkIDs`. In 2002, there was a case of non-reproducible published work, and the problem  turned  out to be that the weights matrix rows were ordered differently from the variable being tested. That's the background. I don't think that this is your use. You could do: `attr(poly2nb(., row.names=as.character(.$FID)), "region.id")`, because you are just re-cycling a column. `poly2nb()` will never work as you want just using `.`, because extra arguments give lots of flexibility. I do not do aesthetics, as you realise.
