### ISSUE TITLE
Better interface between spdep and the tidyverse ?

### ISSUE THREAD

**Issue by katossky** [r-spatial/spdep#41]
I am currently using `spdep` on some spatial data and I find my code to be sometimes akwardly complicated. For instance, for adding neighbors on a `ggplot` graph I am resorting to something like [SAMPLES is the non spatial counterpart of SAMPLES_sf]:

```
library(sf)
library(spdep)

COLUMBUS <- st_read(system.file("shapes/columbus.shp", package="spData")[1])

COLUMBUS %>% ggplot() +
  geom_sf(fill="grey90", col="white") +
  geom_sf(
    color="red",
    data = COLUMBUS %>%
      poly2nb() %>%
      nb2lines(coords= st_coordinates(st_centroid(COLUMBUS))) %>%
      as('sf')
  )
```

... where something like ...

```
COLUMBUS %>% ggplot() +
  geom_sf(fill="grey90", col="white") +
  geom_sf(
    color="red",
    data = find_neighbors(., how="share_border")
  )
```

... would seem more readable and fluid.

I know that spatial data are intrinsically hard, and that not every corner case can be covered. But maybe is it possible to simplify further the use of some common use cases.

**Comment by katossky** [comment]
(it is of course also probable that I missed some functions already existing, and in that case I apologize am willing to help in the documentation, so that other persons like me can find these more easily)

**Comment by rsbivand** [comment]
This is not a reprex. What is SAMPLE_sf and SAMPLE? Provide a reprex using the Columbus data set.

**Comment by katossky** [comment]
I could not find a data set with geometries for my reprex. Sorry :/ `sf` does not seem to contain datasets and `columbus` does not seem to have geometries.

**Comment by katossky** [comment]
I don't think it is duplicate with #40 (which I read), because it is more general. But if you believe that the 2 discussions should happen at the same place, I won't argue :)

**Comment by rsbivand** [comment]
`columbus <- sf::st_read(system.file("shapes/columbus.shp", package="spData")[1]`

The remnant `spdep::columbus` data set is not where to look, it is just to let others using spatial regression to replicate estimation methods. That is what neighbour objects are used for, to the geometries are moot.

**Comment by rsbivand** [comment]
Your suggestion is simplifying more than would be justified ever. The graph is needed principally for analysis, not visualization. So `find_neighbours()` ignores snapping, queen/rook, etc., for contiguity, and is equally oversimplified otherwise. Do things in simple steps not pipelines.

**Comment by katossky** [comment]
```

COLUMBUS %>% ggplot() +
  geom_sf(fill="grey90", col="white") +
  geom_sf(
    color="red",
    data = COLUMBUS %>%
      poly2nb() %>%
      nb2lines(coords= st_coordinates(st_centroid(COLUMBUS))) %>%
      as('sf')
  )
```

**Comment by katossky** [comment]
I don't think you need to trade readability for (over)simplification. `find_neighbors()` can completely have a bunch of options, passed internally to `poly2nb()` and `nb2lines()`. I am just talking of creating wrappers for operations that often come along together, so that _people who want it_ can use them with pipes.

(I wrote `find_neighbors()` just for giving it a name. Probably an other name is better.)

**Comment by rsbivand** [comment]
```
library(sf)
columbus <- st_read(system.file("shapes/columbus.shp", package="spData")[1])
nbs <- spdep::poly2nb(columbus, queen=TRUE)
cents <- st_coordinates(st_geometry(st_centroid(columbus)))
nblns <- spdep::nb2lines(nbs, coords=cents)
library(tmap)
tm_shape(columbus) + tm_fill(fill="grey90") + tm_borders(col="white") + tm_shape(nblns) + tm_lines(col="red")
```
No pipes needed, no **ggplot2** either. Prepare objects before they are needed, so that they can be re-used. Here, neighbours from polygons; centroids from polygons; lines from neighbours and centroids. You could put a set of centroids in the `sf` object as a second `geometry` column, but then you'd have to choose which at each step. You could use:

```
library(ggplot2)
ggplot() + geom_sf(data=columbus, fill="grey90", col="white") + geom_sf(data=st_as_sf(nblns), color="red") + theme_void()
```

**Comment by katossky** [comment]
I never said that you **needed** pipes or ggplot2 for solving my problem. I was just giving _one_ exemple of _one_ case where I felt  syntactic sugar could be added to simplify the workflow of `spdep` users.

I guess what are you saying is that you do not feel the need for supporting verbs/functions to be used with pipes or ggplot2. That's fine. It seems like you prefer creating intermediate objects ; I don't. I get the point if you are re-using them, but here for instance I am computing the centroids only once for the purpose of the map. But, eh, you're the one responsible here, so you decide what in what direction you want to orient your package.

Thank you for teaching me some tricks on the way! (like that one can have extra geometries columns in sf objects or like drawing maps with `tmap`)

**Comment by rsbivand** [comment]
Yes, intermediate objects are available for interrogation if they yield unexpected outcomes:
```
nblns <- spdep::nb2lines(nbs, coords=st_coordinates(cents)[sample(1:length(nbs)),])
tm_shape(columbus) + tm_fill(fill="grey90") + tm_borders(col="white") + tm_shape(nblns) + tm_lines(col="red")
```
Mis-ordering of neighbours with regard to input IDs does happen - here it wouldn't, but it does in longer workflows. Just simplifying things doesn't  work for large `n`, e.g. neighbours of 90,000 LA Census units, but intersecting envelopes to index the entities spatially does, and so on. Almost all use of neighbour objects is for exploratory analysis or modelling, and most such uses need step-by-step approaches.

I will be adding `sf` output to `nb2lines()`, but it isn't obvious how to do this robustly; the function is almost not used at all in packages importing  from spdep. I updated the example above to use `st_point_on_surface()` rather that `st_centroid()` to get points on the polygons.

**Comment by katossky** [comment]
What about a `nb2sf()` function?

**Comment by rsbivand** [comment]
It needs 2 inputs. When I've drafted a resolution to #40 I'll ask for comments.

**Comment by rsbivand** [comment]
@katossky  please see https://github.com/r-spatial/spdep/commit/3f515262cdd4f8c65ea64750eb760c0d0223ea9c#diff-caf2e1584f166ad969f28b9362b3718f
