### ISSUE TITLE
After .travis.yml update, button does not show correct status

### ISSUE THREAD

**Issue by rsbivand** [r-spatial/spdep#43]
@edzer could you please see what I did wrong when I tried to repair **spdep** and **spatialreg** .travis.yml files? They were failing with wrong permissions, so I copied in the recent **sf** file sections. Now they both pass, but the status button is wrong.

**Comment by edzer** [comment]
Looks like a browser caching thing; both are green. I often use a different browser (firefox) for checking such things, or load the image in a new tab.

**Comment by rsbivand** [comment]
Apparently green in Chrome on phone, error in Firefox on phone and laptop. Curious.

**Comment by edzer** [comment]
browser caches are curious things!
