### ISSUE TITLE
two.sided lee.test

### ISSUE THREAD

**Issue by javierfajnolla** [r-spatial/spdep#44]
The help file of lee.test() mentions the option "two.sided" for the "alternative" parameter. However, I get an error whenever I try this option. Do you know if this could be a bug? I can run lee() and lee.mc() with the same data, so I'm confident that the data is suitable for the analysis. "greater" and "less" options also work.

I'm using spdep v1.1-3  
in R version 3.6.1 (2019-07-05)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 16299)

Thanks!

**Comment by rsbivand** [comment]
Taking the example on the man page:

```
library(spdep)
data(oldcol)
col.W <- nb2listw(COL.nb, style="W")
crime <- COL.OLD$CRIME
     
lee.test(crime, crime, col.W, zero.policy=TRUE)
lee.test(crime, crime, col.W, zero.policy=TRUE, alternative="two.sided")
data(boston, package="spData")
lw<-nb2listw(boston.soi)
     
x<-boston.c$CMEDV
y<-boston.c$CRIM
     
lee.test(x, y, lw, zero.policy=TRUE, alternative="less")
lee.test(x, y, lw, zero.policy=TRUE, alternative="two.sided")
```
all seem to work. Please provide a reproducible example, and the verbatim error message shown, together with the |output of `traceback()`.

**Comment by javierfajnolla** [comment]
My bad @rsbivand, thanks for the quick reply. It works fine.

I was using an extra value for the parameter n (number of zones) without properly calling the parameter itself. This happened because I was running the same comparison with `lee()`, and I didn't realise that n was not in `lee.test()`. Hence, the error was: 

`>   lee.test(a$a, f$f,     # x & y
                   lw,             # lw
                   length(a$a),        # This was my "n" in lee(), and it's what the function was considering for a different parameter (maybe "zero.policy"?)
                   zero.policy = TRUE,
                   alternative = "two.sided")
Error in lee.test(a$a, f$f, lw, length(a$a), zero.policy = TRUE, alternative = "two.sided") : 
  objects of different length`

Removing `length(a$a)` solved it.

Thanks for the quick response!
Javier

**Comment by rsbivand** [comment]
OK, thanks.
