### ISSUE TITLE
W matrix with no neighbours in mat2listw()

### ISSUE THREAD

**Issue by chris-dworschak** [r-spatial/spdep#45]
It seems that the function mat2listw() currently does not handle matrix entries with no neighbours, returning a misleading error message. 

When trying to pass on a square W matrix to mat2listw() of which some rows contain only zeros (no neighbours), the following error message is returned:
`Error in print.listw(x): regions with no neighbours found, use zero.policy=TRUE`

Unfortunately, mat2listw() itself does not take the argument zero.policy (does not pass it on to print.listw()). Is there an intention to restore functionality of mat2listw() to handle entries with no neighbours?

**Comment by rsbivand** [comment]
Please provide a reproducible example using a built in data set. The error message you quote is from the `print()` method for `"listw"` objects, where it is needed.

**Comment by chris-dworschak** [comment]
Thank you for your prompt reply. I'm not familiar with built-in contiguity data, but this should serve as a MWE:
```
# a simple contiguity matrix in which the 3rd element has no neighbour:
contiguity.mat <- matrix(
    c(0,1,0,
    1,0,0,
    0,0,0),
    nrow = 3,
    byrow = TRUE
    )

# producing the print() error message reported above:
mat2listw(contiguity.mat)

# print() argument "zero.policy" not supported in mat2listw():
mat2listw(contiguity.mat, zero.policy = TRUE)
```
I was hoping that `mat2listw()` would accept the argument `zero.policy` and pass it on to `print()`. Otherwise, how can contiguity matrices with elements that lack neighbours be processed?

My sincere apologies if this is simply a misunderstanding on my side.

**Comment by rsbivand** [comment]
Resolution: misunderstanding:

```
> o <- mat2listw(contiguity.mat)
> o
Error in print.listw(x) : 
  regions with no neighbours found, use zero.policy=TRUE
> print(o, zero.policy=TRUE)
Characteristics of weights list object:
Neighbour list object:
Number of regions: 3 
Number of nonzero links: 2 
Percentage nonzero weights: 22.22222 
Average number of links: 0.6666667 
1 region with no links:
3

Weights style: M 
Weights constants summary:
  n nn S0 S1 S2
M 2  4  2  4  8
```
