### ISSUE TITLE
Glist formatting for resistance weighted db MEM

### ISSUE THREAD

**Issue by frederikvand** [r-spatial/spdep#49]
Dear spdep admins,

Thank you for the great package! I would like to perform a distance based Moran's Eigenvector Map (db-MEM) for further use in RDA to detect local adaptations. Following the guidelines for spatial weighting I truncated the distance matrix based on the
minimum spanning tree (graph-based MEM) and want to weight my neighbours based on (highly accurate) cumulative landscape resistance values. However, I am unable to get my landscape resistances in the right formatting for weighting.

Neighbour list object:
Number of regions: 29
Number of nonzero links: 164
Percentage nonzero weights: 19.50059
Average number of links: 5.655172

listw <- nb2listw(neighbours, glist=resistance_weights, style="W", zero.policy=NULL)
Error in nb2listw(neighbours, glist = resistance_weights, style = "W", : glist wrong length

The resistance_weights item is a symmetrical cumulative resistance matrix. 

I can directly integrate the resistance matrix with the mat2listw but then I can't truncate the matrix as I understand is advised.

Characteristics of weights list object:
Neighbour list object:
Number of regions: 29
Number of nonzero links: 812
Percentage nonzero weights: 96.55172
Average number of links: 28

Weights style: M
Weights constants summary:
n nn S0 S1 S2
M 29 841 13149.41 902809.7 33894518

Would you have any advise on how to format the resistance matrix for weighting?

Thanks a lot!
With kind regards,
Frederik Van Daele

**Comment by rsbivand** [comment]
Without a fully reproducible example, no idea.

**Comment by frederikvand** [comment]
Included a reproducible example with the symmetrical distance and resistance matrices as input. 
[reproducible_example.zip](https://github.com/r-spatial/spdep/files/5912212/reproducible_example.zip)

Thank you for having a look!

**Comment by frederikvand** [comment]
Included a reproducible example with the symmetrical distance and resistance matrices as input.
reproducible_example.zip

Thank you for having a look!
[reproducible_example.zip](https://github.com/r-spatial/spdep/files/5912256/reproducible_example.zip)

**Comment by frederikvand** [comment]
I am sorry, I just found an explanation in the documentation! 

glist <- vector(mode="list", length=length(neigh))
for (i in seq(along=neigh))
  glist[[i]] <- resistance[i, neigh[[i]]]

listw <- nb2listw(neigh, glist=glist, style="B")
