### ISSUE TITLE
poly2nb queen = FALSE argument is inconsistent 

### ISSUE THREAD

**Issue by christopherkenny** [r-spatial/spdep#50]
Hello,

When using poly2nb, there seems to be an inconsistency between how queen's contiguity is treated between SW-NE corners and SE-NW corners. queen = FALSE does not apply within poly2nb to a SW-NE corner, but does for a SE-NW corner. Below is an example that gets at the issue in a basic 2x2 grid.

```library(sf)
library(spdep)
library(tidyverse)

sq <- st_polygon(list(rbind(c(0,0), c(1,0), c(1,1), c(0,1), c(0,0))))
sq2 <- sq + c(0,1)
sq3 <- sq + c(1,0)
sq4 <- sq + c(1,1)
df <- data.frame(id = 1:4, geometry = c(st_sfc(sq), st_sfc(sq2), st_sfc(sq3), st_sfc(sq4))) %>% st_as_sf()
df %>% ggplot() + geom_sf() + geom_sf_text(aes(label = id))
```
This makes a 2x2 grid, as in the attached file.
![image](https://user-images.githubusercontent.com/28026893/106688081-6a23cf00-659b-11eb-89b3-2fc8e4310f64.png)

Yet, running poly2nb is confusing when using queen = FALSE, as an edge is found for 1-4, but not for 2-3:
```
nb <- poly2nb(df, queen = FALSE)
> nb[[1]]
[1] 2 3 4
> nb[[2]]
[1] 1 4
> nb[[3]]
[1] 1 4
> nb[[4]]
[1] 1 2 3
```

To the best of my knowledge, the example is built correctly, as the intersection of 1 and 4 is a point:
```
> st_intersection(df[1,], df[4,])
Simple feature collection with 1 feature and 2 fields
geometry type:  POINT
dimension:      XY
bbox:           xmin: 1 ymin: 1 xmax: 1 ymax: 1
CRS:            NA
  id id.1    geometry
1  1    4 POINT (1 1)
```

Making a larger grid repeats this issue in the consistently-inconsistent way:
![image](https://user-images.githubusercontent.com/28026893/106688605-6e042100-659c-11eb-89f1-9ab6e9caba09.png)
 
For now, I'm working around this by using `sf::st_relate()` with a number of different patterns to capture rook's contiguity, but spdep is much faster when working with large datasets.

Any thoughts would be much appreciated!
Chris

**Comment by rsbivand** [comment]
`poly2nb()` counts shared boundary points, if >= 2, rook is fulfilled, if >= 1 - queen. What you have noticed is a consequence of more recent enforcement of the condition that polygon objects must be closed, meaning that the closing point repeats the opening point, so inadvertently meeting the rook condition. I'll see whether I can remove the double counting, but rather suggest use of `cell2nb()`, which is intended to generate neighbour objects for regular grids.

**Comment by rsbivand** [comment]
I further see that:
```
library(sf)
sq <- st_polygon(list(rbind(c(0,0), c(1,0), c(1,1), c(0,1), c(0,0))))
sq2 <- sq + c(0,1)
sq3 <- sq + c(1,0)
sq4 <- sq + c(1,1)
gm <- st_sfc(list(sq, sq2, sq3, sq4))
df <- st_as_sf(gm, id=1:4)
plot(st_geometry(df))
text(st_coordinates(st_centroid(gm)), as.character(df$id))
library(spdep)
unclass(poly2nb(df, queen = FALSE))
unclass(cell2nb(2, 2))
library(sp)
gt <- GridTopology(c(0.5, 0.5), c(1, 1), c(2, 2))
sPl <- as(SpatialGrid(gt), "SpatialPolygons")
unclass(poly2nb(sPl, queen=FALSE))
unclass(poly2nb(as(df, "Spatial"), queen=FALSE))
```
So the problem only exists for `"sf"` objects, not for `"SpatialPolygons"` nor when `"sf"` objects are coerced to `"Spatial"`. I'll try to track this down, thanks for your input.

**Comment by rsbivand** [comment]
@christopherkenny please try github version and check that issue is resolved - thanks for your attentiveness to detail!

**Comment by christopherkenny** [comment]
Thank you very much @rsbivand. This works exactly as expected now, both on the grid example and on a test case out of a set of voting district shapefiles.
