### ISSUE TITLE
Nearest Neighbors based on Distance (dnearneigh) in 3D 

### ISSUE THREAD

**Issue by karimhalaseh** [r-spatial/spdep#53]
Hello,

Would it be possible to update dnearneigh to accommodate three-dimensional data, in the same way that knearneigh was updated in the issue referenced below? 

Thanks!

_Originally posted by @karimhalaseh in https://github.com/r-spatial/spdep/issues/38#issuecomment-776880871_

**Comment by rsbivand** [comment]
Please propose a pull request. It is very hard and probably would never be used. As of now, `hypot()` is used in C as a very fast way of finding distances. 3D geodetic distances are not sensible either. Please also explain what this might be used for, given that spatial autocorrelation is 2D in effectively all cases - what is a use case when 3D weights matrices might be used.

**Comment by rsbivand** [comment]
Crucially, provide a small sample dataset to show how 3D distance neighbours can be used in analysis, where the metric in all dimensions is the same. I can see that 2D space + 1D time might be interesting (with different metrics), but have never seen 3D space in geographical work. Are you thinking of medical image data? Voxels?

**Comment by karimhalaseh** [comment]
The application I am using it for is to investigate the spatial autocorrelation of the residuals in predicting the copper grade at dig points within a mine (where the datasets are naturally in 3D). Obviously KNN doesn't make much sense here due to the asymmetry, but I imagined distance bands to quantify neighbors would work quite nicely. 

And apologies, I thought that if the knearneigh function could quickly be adapted to incorporate 3D, then dnearneigh would be too, but looking at the source code I see that they are implemented quite differently!

**Comment by rsbivand** [comment]
It looks as though `RANN::nn2()` can be used with `"radius"` search type. The search is symmetric in all dimensions. If that is what you need, please let me have a smallish example data set (or pint me to such a data set), so that I have something to go on.

**Comment by karimhalaseh** [comment]
Hello Prof. Bivand,

I actually ended up using ```dbscan::frNN()```, which returns an ```frNN``` object where ```frNN$id``` is a list of integer vectors, where each vector contains the ids of the fixed radius nearest neighbours. This was essentially the same structure as an nb object with the difference being how zero-neighbours are dealt with, so I created a pretty simple ```frNN2nb``` function based off the ```knn2nb``` function:

```
frNN2nb <- function(frNN) {
  # check we are dealing with an frNN object input
  if (class(frNN)[1] != "frNN") stop("Not an frNN object")
  
  # make compatible with nb object in spdep
  nn <- frNN$id
  for (i in 1:n)
    if (length(nn[[i]]) == 0) nn[[i]] = c(as.integer(0)) # deal with zero neighbour representation difference   
      
  # assign attributes of object
  attr(nn, "region.id") <- as.character(1:length(nn))
  attr(nn, "sym") <- TRUE # yes, symmetric (if i is a neighbour of j, then j is a neighbour of i because d(i,j)=d(j,i))
  attr(nn, "type") <- "frNN"
  attr(nn, "frNN-eps") <- frNN$eps
    
  # officially convert to class nb
  class(nn) <- "nb"
  nn # return nn
}
```

Note that ```frNN$dist``` contains the distances in the same structure as ```frNN$id```, and so was useful for constructing spatial weights lists based on distance. 

I am not at privilege to send any datasets I have available to me, and am not aware of any publicly available mining data off the top of my head. However, generating dummy data for the columns I shared should be sufficient to test with?

**Comment by rsbivand** [comment]
Yes, I'll look for some XYZ geology data, it needs to be more structured than just 3-column runif(), I think. A problem that remains is that the depth metric may also be m, but it typically works differently. I'll carry on thinking - I also have an idea for unioning a 2D planar and a 1D vertical if the data are bore cores, but I don't have an example (nor for 2D planar and 1D time, which has to be from before to after rather than the reverse. Fallback will be to go with 3D treating all metrics as equivalent.

**Comment by rsbivand** [comment]
Thanks, this was very useful - could you please check both distance and k-nearest neighbours in 3D with your data from the current state of the repo and report back?
