### ISSUE TITLE
nb plot add neighbors

### ISSUE THREAD

**Issue by jpiaskowski** [r-spatial/spdep#55]
Hello,

I am baffled why I see an extra neighbor when I run this code: 

`
library(spdep)
NIN <- data.frame(row = rep(1:11, 22), col = rep(1:22, each = 11))
xy.rook <- cell2nb(nrow = max(NIN$row), ncol = max(NIN$col), type="rook", torus = FALSE)  

library(sf)
rook_matrix <- matrix(c(NIN$col, NIN$row), ncol = 2)
plot(xy.rook, coords = st_multipoint(rook_matrix, dim = "XY"), points = TRUE)
`

I see a gridded rook configuration (as expected), and the addition of a several diagonal lines (running from point 1 to point 222, and running from point 3 to point 224, all the way to point 21 to point 242).  I do not understand why these are present.  I checked the neighbors at those points and they look as expected:

`
sapply(xy.rook, length)
`

Any ideas where these lines are coming from? Thank you. 

<img width="688" alt="Screen Shot 2021-04-02 at 4 08 29 PM" src="https://user-images.githubusercontent.com/8420943/113460454-b50c6800-93cd-11eb-9d7a-0f6153b68eb3.png">

**Comment by rsbivand** [comment]
Thank you for asking. This is related to https://github.com/r-spatial/spdep/issues/20 @ChimskyChim , so more work will be needed. In your case:
```
xy.rook <- cell2nb(nrow = max(NIN$row), ncol = max(NIN$col), type="rook", torus = FALSE, legacy=TRUE)
```
restores expected behaviour. I'll set up some more thorough tests to check what is going on.

**Comment by jpiaskowski** [comment]
Fantastic, thank you so much!

**Comment by rsbivand** [comment]
I'll carry on looking at this, because `legacy=` should be false. I'll let you know on this issue when I feel more confident about what should have happened.

**Comment by rsbivand** [comment]
The complete analysis is as follows:

```
library(spdep)
NIN <- data.frame(row = rep(1:11, 22), col = rep(1:22, each = 11))
xy.rook <- cell2nb(nrow = max(NIN$row), ncol = max(NIN$col), type="rook", legacy = FALSE)
```
with `xy.rook` correct. What causes the problem you report above is the relative ordering/cycling of rows and columns in 

```
rook_matrix <- matrix(c(NIN$col, NIN$row), ncol = 2)
plot(xy.rook, coords = rook_matrix, points = TRUE)
```
```
> head(rook_matrix)
     [,1] [,2]
[1,]    1    1
[2,]    1    2
[3,]    1    3
[4,]    1    4
[5,]    1    5
[6,]    1    6
```

![image](https://user-images.githubusercontent.com/10198404/113713836-10996700-96e8-11eb-810f-ec6662718839.png)
```
rook_matrix <- st_as_sf(expand.grid(col=1:22, row=1:11), coords=c("col", "row"))
plot(xy.rook, coords = st_geometry(rook_matrix), points = TRUE)
```
![image](https://user-images.githubusercontent.com/10198404/113714563-cfee1d80-96e8-11eb-80ff-6dc9a07ee1c8.png)
```
> head(st_geometry(rook_matrix))
Geometry set for 6 features 
Geometry type: POINT
Dimension:     XY
Bounding box:  xmin: 1 ymin: 1 xmax: 6 ymax: 1
CRS:           NA
First 5 geometries:
POINT (1 1)
POINT (2 1)
POINT (3 1)
POINT (4 1)
POINT (5 1)
```
So finally the way you cycled the rows and columns in creating NIN using `rep()` created the plotting issue; using `expand.grid()`, the points also cycle the other dimension faster:
```
NINo <- data.frame(row = rep(1:11, each=22), col = rep(1:22, 11))
xy.rook <- cell2nb(nrow = max(NINo$row), ncol = max(NINo$col), type="rook", legacy = FALSE)
rook_matrix <- matrix(c(NINo$col, NINo$row), ncol = 2)
plot(xy.rook, coords = rook_matrix, points = TRUE)
```
![image](https://user-images.githubusercontent.com/10198404/113715186-7cc89a80-96e9-11eb-807d-a5bae877db06.png)

**Comment by jpiaskowski** [comment]
nice, thanks. All good ideas.

**Comment by jpiaskowski** [comment]
ha, you should try your code with `Legacy = TRUE'. That plot is *crazy*.
