### ISSUE TITLE
spData dependency does not load

### ISSUE THREAD

**Issue by marcbosch-idencity** [r-spatial/spdep#60]
As it says in the title, when trying to load spdata, it returns the following error. I tried re-installing spdata but then when trying to load spdep, RStudio freezes and, when opening a new session, it returns the same error.

```
Loading required package: sp
Loading required package: spData
Error: package or namespace load failed for ‘spData’ in .doLoadActions(where, attach):
 error in load action .__A__.1 for package raster: loadModule(module = "spmod", what = TRUE, env = ns, loadNow = TRUE): Unable to load module "spmod": function 'Rcpp_precious_remove' not provided by package 'Rcpp'
Error: package ‘spData’ could not be loaded
```

 Is there any way around this?
I'm using the following versions on a Lenovo Thinkbook 14 (16 GB RAM, intel core i5 from 2020) and the session is as follows,
spData: 0.3.10
spdep: 1.1-8

R version 4.1.0 (2021-05-18)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19041)

Thank you so much.

**Comment by marcbosch-idencity** [comment]
Closed, found a solution. Sorry for the inconvenience.

**Comment by CaiusJard** [comment]
Can you comment what it was? I'm also seeing an error " function 'Rcpp_precious_remove' not provided by package 'Rcpp' "

**Comment by Tingting-Xie** [comment]
> Can you comment what it was? I'm also seeing an error " function 'Rcpp_precious_remove' not provided by package 'Rcpp' "

reinstall Rcpp
