### ISSUE TITLE
Confusing warning to install "spatialreg" during install

### ISSUE THREAD

**Issue by mjsteinbaugh** [r-spatial/spdep#63]
Hi I'm seeing this warning pop up on install on macOS for spdep, even though spatialreg is already installed:

```
** byte-compile and prepare package for lazy loading
Warning in eval(exprs[i], envir) : install the spatialreg package
Calls: <Anonymous> ... tryCatchOne -> doTryCatch -> sys.source -> eval -> eval
** help
```

**Comment by rsbivand** [comment]
This is not a problem, and is related to the splitting out of modelling functions to **spatialreg** https://github.com/r-spatial/spdep/issues/31. Fairly soon, **spdep** 1.2 will be ready, removing ties to **spatialreg**.

**Comment by mjsteinbaugh** [comment]
OK thanks!
