### ISSUE TITLE
Is there a limit to the file size/number of points that can be analysed?

### ISSUE THREAD

**Issue by anmolter** [r-spatial/spdep#7]
I am trying to run a linear model with spatially autocorrelated dependent variables using `lagsarlm.` The dataset contains 2521 unique locations and the spatial weights matrix was created in ArcGIS 10.4.1, exported as dbf and then saved as gwt.  Loading the data and reading in the spatial weights matrix seems to work (see output below), but R crashes when I try to run `lagsarlm.` I've tried running it in RStudio, R console and via command prompt, but it always crashes. My gut feeling is that R can't handle the amount of data; however, 2500 points and a 5Mb spatial weights matrix doesn't seem that large to me.

I'm using Microsoft R Open 3.4.3 on Windows 8.1 with a  2.40GHz processor and 32GB of RAM. 

Here is the output file I get when running it from command prompt:
```
R version 3.4.3 (2017-11-30) -- "Kite-Eating Tree"
Copyright (C) 2017 The R Foundation for Statistical Computing
Platform: x86_64-w64-mingw32/x64 (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

Microsoft R Open 3.4.3
The enhanced R distribution from Microsoft
Microsoft packages Copyright (C) 2017 Microsoft Corporation

Using the Intel MKL for parallel mathematical computing (using 6 cores).

Default CRAN mirror snapshot taken on 2018-01-01.
See: https://mran.microsoft.com/.

> library(spdep)
Loading required package: sp
Loading required package: Matrix
Loading required package: spData
> 
> sessionInfo()
R version 3.4.3 (2017-11-30)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 8.1 x64 (build 9600)

Matrix products: default

locale:
[1] LC_COLLATE=English_United Kingdom.1252 
[2] LC_CTYPE=English_United Kingdom.1252   
[3] LC_MONETARY=English_United Kingdom.1252
[4] LC_NUMERIC=C                           
[5] LC_TIME=English_United Kingdom.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] spdep_0.7-4          spData_0.2.6.0       Matrix_1.2-12       
[4] sp_1.2-6             RevoUtils_10.0.7     RevoUtilsMath_10.0.1

loaded via a namespace (and not attached):
 [1] lattice_0.20-35     deldir_0.1-14       gtools_3.5.0       
 [4] spDataLarge_0.2.3.1 MASS_7.3-47         grid_3.4.3         
 [7] nlme_3.1-131        coda_0.19-1         gdata_2.18.0       
[10] LearnBayes_2.15     gmodels_2.16.2      boot_1.3-20        
[13] splines_3.4.3       compiler_3.4.3      expm_0.999-2       
> 
> #set working directory
> setwd("C:/ExtHDD_backup/BRIT/Spatial_data/SpatReg")
> 
> ########################################################
> ##load data
> ########################################################
> d<-read.csv("testdat.csv",stringsAsFactors=FALSE)
> 
> head(d)
  practice_id wtIMD_score wtInc_score Cluster
1           1    29.16808    0.203888     hot
2           2    29.74406    0.213128     hot
3           4    34.31226    0.224040     hot
4           6    32.49078    0.231183     hot
5           8    51.58860    0.358767     hot
6           9    35.28521    0.233471     hot
> str(d)
'data.frame':	2521 obs. of  4 variables:
 $ practice_id: int  1 2 4 6 8 9 12 14 16 17 ...
 $ wtIMD_score: num  29.2 29.7 34.3 32.5 51.6 ...
 $ wtInc_score: num  0.204 0.213 0.224 0.231 0.359 ...
 $ Cluster    : chr  "hot" "hot" "hot" "hot" ...
> 
> ##create list of from IDs
> from_IDs<-sort(unique(d$practice_id))
> 
> length(from_IDs)
[1] 2521
> 
> ##########################################################
> ##read in spatial weights matrix
> ##########################################################
> nb1<-read.gwt2nb("All_spat_w_SEL.GWT",region.id = from_IDs)
Warning messages:
1: In read.gwt2nb("All_spat_w_SEL.GWT", region.id = from_IDs) :
  Old-style GWT file
2: In read.gwt2nb("All_spat_w_SEL.GWT", region.id = from_IDs) :
  111, 119, 183, 2263, 4741, 4890, 6231, 7750 are not destinations
> nb1.w <- nb2listw(nb1, style="B",zero.policy = TRUE)
> print(nb1.w)
Characteristics of weights list object:
Neighbour list object:
Number of regions: 2521 
Number of nonzero links: 269993 
Percentage nonzero weights: 4.248218 
Average number of links: 107.0976 
Non-symmetric neighbours list

Weights style: B 
Weights constants summary:
     n      nn     S0     S1        S2
B 2521 6355441 269993 519153 166596259
> 
> ################################################################
> ##lm with spatial autocorrelation in dependent variable
> ################################################################
> dlag<-lagsarlm(wtIMD_score~Cluster, data=d, nb1.w)
```

**Comment by rsbivand** [comment]
Please provide a fully reproducible example (upload script and data to a server and post address or attach here). The 2015 [JSS](https://www.jstatsoft.org/article/view/v063i18) paper is using a larger data set in all comparisons, so it is not the size. The definition of [R crashes](https://www.r-project.org/posting-guide.html) is clear, and if R error-exits, it will provide a message. Can you make MKL run on one core - this is so unusual that MKL seems to be the thing to control. It will give no assistance except perhaps in solving the eigenproblem, and you can do that first yourself. Also cross-check with method="LU", or if your imported weights are symmetric, method="Matrix". Don't use RStudio to reduce the number of R sessions until this is debugged.

**Comment by anmolter** [comment]
[dat4github.zip](https://github.com/r-spatial/spdep/files/1668166/dat4github.zip)
I've re-run the code with standard R 3.4.3 (only one core)  and I have the same problem. I have also added method="LU" to the code, but still the same problem. The error message I get is "R for Windows terminal front-end has stopped working" and when clicking debug: "An unhandled win32 exception occurred in Rterm.exe [10596]".
I've attached my data files and code.

**Comment by rsbivand** [comment]
One of your errors was `stringsAsFactors=FALSE`, the mode of `d$Cluster` is `"character"`, which cannot be lagged. A further error, and the cause of the problem, seems to be your GWT file, which uses IDs, not indices in 1:2521.

**Comment by rsbivand** [comment]
It looks as though the GWT file contains many destinations which are not in the set defined by `d$practice_id`. In the development version on github, I've added traps for this:

```
> library(spdep)
Loading required package: sp
Loading required package: Matrix
Loading required package: spData
> d<-read.csv("testdat.csv")
> nb1<-read.gwt2nb("spatweights.GWT",region.id = d$practice_id)
Error: !anyNA(regddij) is not TRUE
In addition: Warning message:
In read.gwt2nb("spatweights.GWT", region.id = d$practice_id) :
  Old-style GWT file
> ij <- read.table("spatweights.GWT", skip=1)
> summary(match(d$practice_id, ij[,1]))
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
      1   42318  153080  135472  219740  269975 
> summary(ij)
       V1              V2              V3   
 Min.   :    1   Min.   :    1   Min.   :1  
 1st Qu.: 3429   1st Qu.: 3428   1st Qu.:1  
 Median : 4285   Median : 4287   Median :1  
 Mean   : 5287   Mean   : 5287   Mean   :1  
 3rd Qu.: 5796   3rd Qu.: 5792   3rd Qu.:1  
 Max.   :16295   Max.   :16295   Max.   :1  
> summary(match(ij[,1], d$practice_id))
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
      1     786    1152    1256    1650    2521 
> summary(match(ij[,2], d$practice_id))
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's 
    1.0   775.2  1116.0  1224.3  1597.0  2521.0   20807 
> head(ij[,2][!(ij[,2] %in% d$practice_id)])
[1] 26 37 37 37 26 37
> d$practice_id[1:50]
 [1]   1   2   4   6   8   9  12  14  16  17  18  19  20  21  23  24  25  27  28
[20]  31  32  33  34  35  36  38  40  41  44  47  48  49  53  54  55  59  60  62
[39]  65  67  69  71  72  78  83  88 102 103 105 106
```
Wouldn't it be easier to create the neighbours in R? Your export from Arc was clearly unsound, and the R reading function trusted what it read without checking.

**Comment by anmolter** [comment]
Unfortunately, I don't think I can use R to create my spatial weights, because I need a combination of fixed distances and n nearest neighbours (if there are no neighbours within the fixed distance). I don't think this is possible in R, but please correct me if I'm wrong.
However, based on your comments I've worked out what went wrong with my spatial weights matrix: the data I'm working with is a subset of a larger dataset, therefore there are neighbour IDs, which no longer appear in the origins IDs. I've worked around this by removing rows with neighbours that are not origins from the GWT file and I've recoded the IDs into indices. Finally, I've set `stringsAsFactors=TRUE` and now `lagsarlm` is running fine.
Thank you for all your help!

**Comment by rsbivand** [comment]
Might `union.nb()` work for you? 

```
library(spdep)
data(columbus)
k1 <- knn2nb(knearneigh(coords, k=1))
max(unlist(nbdists(k1, coords)))
# [1] 0.6188642
dnb <- dnearneigh(coords, 0, 0.5)
dnb
# Neighbour list object:
# Number of regions: 49 
# Number of nonzero links: 170 
# Percentage nonzero weights: 7.080383 
# Average number of links: 3.469388 
# 4 regions with no links:
# 1 3 6 21
knb <- knn2nb(knearneigh(coords, k=4))
knb
# Neighbour list object:
# Number of regions: 49 
# Number of nonzero links: 196 
# Percentage nonzero weights: 8.163265 
# Average number of links: 4 
# Non-symmetric neighbours list
dknb <- union.nb(dnb, knb)
dknb
# Neighbour list object:
# Number of regions: 49 
# Number of nonzero links: 237 
# Percentage nonzero weights: 9.870887 
# Average number of links: 4.836735 
# Non-symmetric neighbours list
```
and optionally make symmetric:
```
dknb_sym <- make.sym.nb(dknb)
dknb_sym
# Neighbour list object:
# Number of regions: 49 
# Number of nonzero links: 268 
# Percentage nonzero weights: 11.16202 
# Average number of links: 5.469388 
```

**Comment by anmolter** [comment]
This is not quite what I need, because for each origin it uses both neighbours with distance x and the k nearest neighbours. I only want to use the k nearest neighbours, if there are zero neighbours within distance x. If there are any neighbours within distance x, I only want to use these. However, I think this can be achieved by using `droplinks` prior to `union.nb`:

` knb.toInsert<-droplinks(knb,c(2,4,5,7:20,22:49))
Warning message:
In droplinks(knb, c(2, 4, 5, 7:20, 22:49)) : setting sym to FALSE
dknb.2<-union.nb(dnb, knb.toInsert)
 
 dknb.2[[1]] # should use data from nearest neighbours
[1] 2 3 4 8
 dnb[[1]]
[1] 0
 knb.toInsert[[1]]
[1] 2 3 4 8
 dknb.2[[2]] # should use data from fixed distance
[1] 4
 dnb[[2]]
[1] 4
 knb.toInsert[[2]]
[1] 0`
