### ISSUE TITLE
units?

### ISSUE THREAD

**Issue by KhatriVivek** [r-spatial/spdep#81]
Hello.

For the dnearest function, are the units for distance in meters?

i.e.
dnearneigh(mo.coords, d1 = 0, d2 = 32000, 
                      row.names = mo$GEOID)

Best

Vivek

**Comment by rsbivand** [comment]
It  depends on what `x` is: if in geographical coordinates, kilometres, if not, in the metric of the points (metres, surveyor's feet, etc.). I'll try to improve the help page.
