### ISSUE TITLE
Ability to remove self after using `include.self()`

### ISSUE THREAD

**Issue by JosiahParry** [r-spatial/spdep#83]
Very mild suggestion / request. Presently, using spdep one can add the diagonal elements of the neighbor matrix using `include.self()`. However there is no easy way to remove the self-element from the `nb` object. 

Take the following example 

```r
g <- st_as_sf(Guerry::gfrance85)

nb <- poly2nb(g)
listw <- nb2listw(nb)

lag.listw(listw, g$Crime_prop)

nb <- include.self(nb)
listw <- nb2listw(nb)

lag.listw(listw, g$Crime_prop)
```

The only way to return nb to remove the self (seems philosophical) from nb is by recreating it with `poly2nb()`. I'd propose a function `remove.self()` to complement `include.self()`.

A suggested implementation

```r
remove.self <- function(nb) {
  
  if (is.null(attr(nb, "self.included")))  stop("Self not included. Cannot remove.")
  
  for (i in 1:length(nb)) {
    nb[[i]] <- nb[[i]][-which(nb[[i]] == i)]
  }
  
  attr(nb, "self.included") <- NULL
  
  return(nb)
}
```

**Comment by rsbivand** [comment]
Thanks!
