### ISSUE TITLE
Impacts for Spatial Duirbin Model

### ISSUE THREAD

**Issue by Ebobrovskaya** [r-spatial/spdep#84]
I am trying to calculate impacts for Spatial Durbin Model. My problem is that I need one of the variables to have no spatial lag, because this variable is related to location.  Unfortunately, this will result in the error: "non-matched coefficient pairs". Is there a way to fix this?

**Comment by rsbivand** [comment]
This is a question to **spatialreg**, see the use of the `Durbin=` argument as a formula.

**Comment by Ebobrovskaya** [comment]
Thank you!
