### ISSUE TITLE
R studio crashes when loading spdep

### ISSUE THREAD

**Issue by petridinik** [r-spatial/spdep#86]
Hello, 

I am dealing with a "fatal error" message when I try to run require(spdep). Followed instructions on installing a previous version of R (R 4-1-3 in specific), however the problem was not resolved. 

What information do you need from me and actions do I need to take so as to fix this?

Thank you in advance, 

Nikolaos.

**Comment by rsbivand** [comment]
Output of sessionInfo(), run outside rstudio, and repeated after running update.packages(). I think you need to run update.packages(checkBuild=TRUE) and sort out the packages so that they agree with your current R version, nothing to do with spdep.

**Comment by petridinik** [comment]
I attach you my sessionInfo() details. 

> sessionInfo()
R version 4.1.3 (2022-03-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19044)

Matrix products: default

locale:
[1] LC_COLLATE=Greek_Greece.1253  LC_CTYPE=Greek_Greece.1253    LC_MONETARY=Greek_Greece.1253
[4] LC_NUMERIC=C                  LC_TIME=Greek_Greece.1253    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_4.1.3 tools_4.1.3

How do I run outside Rstudio (sorry for that, I use R only for statistical analysis)? In terms of update packages, I did it last week.

**Comment by rsbivand** [comment]
Find R in the apps/programmes menu, chooose R-4.1.3; should open `Rgui.exe`. Or try `C:\Rpgram Files\R\R-4.1.3\bin\x64\Rgui.exe`. RStudio is not R, it is an IDE installed on top of R. Almost certainly your libraries are messed up (mixed R versions of packages), but **spdep** does use **sf** and other packages using external libraries. What happens with:
```
library(sp)
library(spData)
library(sf)
```
Do any of these fail? If so, the failing package should be re-installed.

**Comment by mkclement** [comment]
Dear Prof Bivan,

I am facing the same problem as Nikolaos. I followed your advice to see if the problem can be solved, but this was not the case. Even as I am writing this comment, the challenge is there. I am using R version 4.2.1, and Rstudio 2022.07.1 Build 554. I would highly appreciate your assistance.

Regards,
Clement

**Comment by rsbivand** [comment]
@petridinik did not respond to my clear request for information. @mkclement - what is your platform (OS, if macOS whether M1 or Intel)? Outside Rstudio, run:
```
library(sp)
library(spData)
library(sf)
```
after `update.packages(checkBuild=TRUE)` with no other packages loaded or attached (report the output of `sessionInfo()`). Then, `library(spdep)`. Do any of these fail? If no failures, repeat inside Rstudio. Any failures now?

**Comment by mkclement** [comment]
Dear Prof Bivan,

Thanks for a prompt reply. I am using Microsoft windows. I have done as suggested outside Rstudion, sp loaded without problem, but spData could not and R crushed. 

Regards,
Clement

**Comment by rsbivand** [comment]
R could not "crash". Please re-install spData and raster from CRAN, both pass their CRAN checks. Do report the output of sessionInfo() showing package versions.

**Comment by mkclement** [comment]
Dear Prof Bivan,

R version 4.2.1 (2022-06-23 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19043)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.utf8 
[2] LC_CTYPE=English_United States.utf8   
[3] LC_MONETARY=English_United States.utf8
[4] LC_NUMERIC=C                          
[5] LC_TIME=English_United States.utf8    

attached base packages:
character(0)

other attached packages:
[1] spData_2.0.1

loaded via a namespace (and not attached):
 [1] compiler_4.2.1    graphics_4.2.1    tools_4.2.1       utils_4.2.1      
 [5] performance_0.9.1 grDevices_4.2.1   stats_4.2.1       datasets_4.2.1   
 [9] insight_0.18.0    methods_4.2.1     base_4.2.1       

###########

R version 4.2.1 (2022-06-23 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19043)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.utf8 
[2] LC_CTYPE=English_United States.utf8   
[3] LC_MONETARY=English_United States.utf8
[4] LC_NUMERIC=C                          
[5] LC_TIME=English_United States.utf8    

attached base packages:
character(0)

other attached packages:
[1] raster_3.5-21

loaded via a namespace (and not attached):
 [1] compiler_4.2.1    graphics_4.2.1    tools_4.2.1       utils_4.2.1      
 [5] performance_0.9.1 grDevices_4.2.1   stats_4.2.1       datasets_4.2.1   
 [9] insight_0.18.0    methods_4.2.1     base_4.2.1

**Comment by edzer** [comment]
>  attached base packages:
> character(0)

looks worrisome: time to re-install R completely?

**Comment by mkclement** [comment]
Thanks a lot. I am re-installing R as suggested.


*Dr Clement Mulamba, PhD (UJ) *
*Lecturer*
*School of Economics*
*College of Business and Economics*
*University of Johannesburg*

*Conference interpreter and translator*
*English to French and vice versa.*

*Cell and WhatsApp: +27(0)71 443 1958*
Facebook: Kabeya Clement Mulamba
Twitter: @ClementMulamba2
https://orcid.org/0000-0001-6428-8814

**Comment by rsbivand** [comment]
On a fresh Windows install of 4.2.1, it is:

```
attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base  
```
