### ISSUE TITLE
A mistake in nb2listwdist.R

### ISSUE THREAD

**Issue by esheeep** [r-spatial/spdep#87]
Hi Roger and Rene! 
Thanks a lot for making this package! I just found out there might be a little mistake in 'nb2listwdist.R' code in line 81-84:
` max_finite <- max(is.finite(unlist(vlist)))`
   ` for(i in 1:n) {
      vlist[[i]][which(is.infinite(vlist[[i]]))] <- max_finite
    }`
The 'max_finite' is the max of a logical object, so it can only be 1 or 0, rather than the actual maximum value among all finite weights. 
I'm unsure whether I understood this code correctly, but I hope it will help!

Best wishes,
Guan

**Comment by rsbivand** [comment]
Could you please provide a reproducible example; I think I can see a problem but a reprex would show that it is your problem.
