### ISSUE TITLE
Couldn't install spdep on ubuntu 

### ISSUE THREAD

**Issue by Fingernight1** [r-spatial/spdep#88]
![image](https://user-images.githubusercontent.com/44545378/185255589-7df76e47-1473-4139-bb14-fac992289171.png)
When I install.packages("spdep") via source or url or other ways. It didn't work and occurs this Error.
Could someone help me with this issue?
Thanks in advanced~!
  ** R
  ** data
  ** inst
  ** byte-compile and prepare package for lazy loading
  double free or corruption (out)
  Aborted (core dumped)
  ERROR: lazy loading failed for package ‘spdep’
  * removing ‘/home/jins/anaconda3/envs/R_new/lib/R/library/spdep’
  Warning message:
  In install.packages("/home/jins/spdep_1.2-6.tar.gz", repos = NULL,  :
    installation of package ‘/home/jins/spdep_1.2-6.tar.gz’ had non-zero exit status

**Comment by rsbivand** [comment]
Please always include full sessionInfo() output. Please do run update.packages(check.build=TRUE) before trying to install any package. Then install spData, sf, sp in turn before spdep. Report back on progress.

**Comment by rsbivand** [comment]
Also, anaconda is not checked or supported, so for non-standard installations, no help is available.

**Comment by Fingernight1** [comment]
Thanks for your time~Here is all the output when I install.package("spdep")

* installing *source* package ‘spdep’ ...
** using staged installation
** libs
x86_64-conda-linux-gnu-cc -I"/home/jins/anaconda3/envs/R_new/lib/R/include" -DNDEBUG   -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /home/jins/anaconda3/envs/R_new/include -I/home/jins/anaconda3/envs/R_new/include -Wl,-rpath-link,/home/jins/anaconda3/envs/R_new/lib   -fpic  -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/jins/anaconda3/envs/R_new/include -fdebug-prefix-map=/home/conda/feedstock_root/build_artifacts/r-base-split_1659993824316/work=/usr/local/src/conda/r-base-4.2.1 -fdebug-prefix-map=/home/jins/anaconda3/envs/R_new=/usr/local/src/conda-prefix  -c card.c -o card.o
x86_64-conda-linux-gnu-cc -I"/home/jins/anaconda3/envs/R_new/lib/R/include" -DNDEBUG   -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /home/jins/anaconda3/envs/R_new/include -I/home/jins/anaconda3/envs/R_new/include -Wl,-rpath-link,/home/jins/anaconda3/envs/R_new/lib   -fpic  -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/jins/anaconda3/envs/R_new/include -fdebug-prefix-map=/home/conda/feedstock_root/build_artifacts/r-base-split_1659993824316/work=/usr/local/src/conda/r-base-4.2.1 -fdebug-prefix-map=/home/jins/anaconda3/envs/R_new=/usr/local/src/conda-prefix  -c dfs_ncomp.c -o dfs_ncomp.o
x86_64-conda-linux-gnu-cc -I"/home/jins/anaconda3/envs/R_new/lib/R/include" -DNDEBUG   -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /home/jins/anaconda3/envs/R_new/include -I/home/jins/anaconda3/envs/R_new/include -Wl,-rpath-link,/home/jins/anaconda3/envs/R_new/lib   -fpic  -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/jins/anaconda3/envs/R_new/include -fdebug-prefix-map=/home/conda/feedstock_root/build_artifacts/r-base-split_1659993824316/work=/usr/local/src/conda/r-base-4.2.1 -fdebug-prefix-map=/home/jins/anaconda3/envs/R_new=/usr/local/src/conda-prefix  -c dnn.c -o dnn.o
x86_64-conda-linux-gnu-cc -I"/home/jins/anaconda3/envs/R_new/lib/R/include" -DNDEBUG   -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /home/jins/anaconda3/envs/R_new/include -I/home/jins/anaconda3/envs/R_new/include -Wl,-rpath-link,/home/jins/anaconda3/envs/R_new/lib   -fpic  -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/jins/anaconda3/envs/R_new/include -fdebug-prefix-map=/home/conda/feedstock_root/build_artifacts/r-base-split_1659993824316/work=/usr/local/src/conda/r-base-4.2.1 -fdebug-prefix-map=/home/jins/anaconda3/envs/R_new=/usr/local/src/conda-prefix  -c gabriel.c -o gabriel.o
x86_64-conda-linux-gnu-cc -I"/home/jins/anaconda3/envs/R_new/lib/R/include" -DNDEBUG   -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /home/jins/anaconda3/envs/R_new/include -I/home/jins/anaconda3/envs/R_new/include -Wl,-rpath-link,/home/jins/anaconda3/envs/R_new/lib   -fpic  -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/jins/anaconda3/envs/R_new/include -fdebug-prefix-map=/home/conda/feedstock_root/build_artifacts/r-base-split_1659993824316/work=/usr/local/src/conda/r-base-4.2.1 -fdebug-prefix-map=/home/jins/anaconda3/envs/R_new=/usr/local/src/conda-prefix  -c gearyw.c -o gearyw.o
x86_64-conda-linux-gnu-cc -I"/home/jins/anaconda3/envs/R_new/lib/R/include" -DNDEBUG   -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /home/jins/anaconda3/envs/R_new/include -I/home/jins/anaconda3/envs/R_new/include -Wl,-rpath-link,/home/jins/anaconda3/envs/R_new/lib   -fpic  -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/jins/anaconda3/envs/R_new/include -fdebug-prefix-map=/home/conda/feedstock_root/build_artifacts/r-base-split_1659993824316/work=/usr/local/src/conda/r-base-4.2.1 -fdebug-prefix-map=/home/jins/anaconda3/envs/R_new=/usr/local/src/conda-prefix  -c gsymtest.c -o gsymtest.o
x86_64-conda-linux-gnu-cc -I"/home/jins/anaconda3/envs/R_new/lib/R/include" -DNDEBUG   -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /home/jins/anaconda3/envs/R_new/include -I/home/jins/anaconda3/envs/R_new/include -Wl,-rpath-link,/home/jins/anaconda3/envs/R_new/lib   -fpic  -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/jins/anaconda3/envs/R_new/include -fdebug-prefix-map=/home/conda/feedstock_root/build_artifacts/r-base-split_1659993824316/work=/usr/local/src/conda/r-base-4.2.1 -fdebug-prefix-map=/home/jins/anaconda3/envs/R_new=/usr/local/src/conda-prefix  -c init.c -o init.o
x86_64-conda-linux-gnu-cc -I"/home/jins/anaconda3/envs/R_new/lib/R/include" -DNDEBUG   -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /home/jins/anaconda3/envs/R_new/include -I/home/jins/anaconda3/envs/R_new/include -Wl,-rpath-link,/home/jins/anaconda3/envs/R_new/lib   -fpic  -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/jins/anaconda3/envs/R_new/include -fdebug-prefix-map=/home/conda/feedstock_root/build_artifacts/r-base-split_1659993824316/work=/usr/local/src/conda/r-base-4.2.1 -fdebug-prefix-map=/home/jins/anaconda3/envs/R_new=/usr/local/src/conda-prefix  -c insiders.c -o insiders.o
x86_64-conda-linux-gnu-cc -I"/home/jins/anaconda3/envs/R_new/lib/R/include" -DNDEBUG   -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /home/jins/anaconda3/envs/R_new/include -I/home/jins/anaconda3/envs/R_new/include -Wl,-rpath-link,/home/jins/anaconda3/envs/R_new/lib   -fpic  -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/jins/anaconda3/envs/R_new/include -fdebug-prefix-map=/home/conda/feedstock_root/build_artifacts/r-base-split_1659993824316/work=/usr/local/src/conda/r-base-4.2.1 -fdebug-prefix-map=/home/jins/anaconda3/envs/R_new=/usr/local/src/conda-prefix  -c jc.c -o jc.o
x86_64-conda-linux-gnu-cc -I"/home/jins/anaconda3/envs/R_new/lib/R/include" -DNDEBUG   -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /home/jins/anaconda3/envs/R_new/include -I/home/jins/anaconda3/envs/R_new/include -Wl,-rpath-link,/home/jins/anaconda3/envs/R_new/lib   -fpic  -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/jins/anaconda3/envs/R_new/include -fdebug-prefix-map=/home/conda/feedstock_root/build_artifacts/r-base-split_1659993824316/work=/usr/local/src/conda/r-base-4.2.1 -fdebug-prefix-map=/home/jins/anaconda3/envs/R_new=/usr/local/src/conda-prefix  -c knn.c -o knn.o
x86_64-conda-linux-gnu-cc -I"/home/jins/anaconda3/envs/R_new/lib/R/include" -DNDEBUG   -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /home/jins/anaconda3/envs/R_new/include -I/home/jins/anaconda3/envs/R_new/include -Wl,-rpath-link,/home/jins/anaconda3/envs/R_new/lib   -fpic  -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/jins/anaconda3/envs/R_new/include -fdebug-prefix-map=/home/conda/feedstock_root/build_artifacts/r-base-split_1659993824316/work=/usr/local/src/conda/r-base-4.2.1 -fdebug-prefix-map=/home/jins/anaconda3/envs/R_new=/usr/local/src/conda-prefix  -c lagw.c -o lagw.o
x86_64-conda-linux-gnu-cc -I"/home/jins/anaconda3/envs/R_new/lib/R/include" -DNDEBUG   -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /home/jins/anaconda3/envs/R_new/include -I/home/jins/anaconda3/envs/R_new/include -Wl,-rpath-link,/home/jins/anaconda3/envs/R_new/lib   -fpic  -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/jins/anaconda3/envs/R_new/include -fdebug-prefix-map=/home/conda/feedstock_root/build_artifacts/r-base-split_1659993824316/work=/usr/local/src/conda/r-base-4.2.1 -fdebug-prefix-map=/home/jins/anaconda3/envs/R_new=/usr/local/src/conda-prefix  -c listw2sn.c -o listw2sn.o
x86_64-conda-linux-gnu-cc -I"/home/jins/anaconda3/envs/R_new/lib/R/include" -DNDEBUG   -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /home/jins/anaconda3/envs/R_new/include -I/home/jins/anaconda3/envs/R_new/include -Wl,-rpath-link,/home/jins/anaconda3/envs/R_new/lib   -fpic  -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/jins/anaconda3/envs/R_new/include -fdebug-prefix-map=/home/conda/feedstock_root/build_artifacts/r-base-split_1659993824316/work=/usr/local/src/conda/r-base-4.2.1 -fdebug-prefix-map=/home/jins/anaconda3/envs/R_new=/usr/local/src/conda-prefix  -c nbdists.c -o nbdists.o
x86_64-conda-linux-gnu-cc -I"/home/jins/anaconda3/envs/R_new/lib/R/include" -DNDEBUG   -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /home/jins/anaconda3/envs/R_new/include -I/home/jins/anaconda3/envs/R_new/include -Wl,-rpath-link,/home/jins/anaconda3/envs/R_new/lib   -fpic  -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/jins/anaconda3/envs/R_new/include -fdebug-prefix-map=/home/conda/feedstock_root/build_artifacts/r-base-split_1659993824316/work=/usr/local/src/conda/r-base-4.2.1 -fdebug-prefix-map=/home/jins/anaconda3/envs/R_new=/usr/local/src/conda-prefix  -c polypoly.c -o polypoly.o
x86_64-conda-linux-gnu-cc -I"/home/jins/anaconda3/envs/R_new/lib/R/include" -DNDEBUG   -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /home/jins/anaconda3/envs/R_new/include -I/home/jins/anaconda3/envs/R_new/include -Wl,-rpath-link,/home/jins/anaconda3/envs/R_new/lib   -fpic  -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/jins/anaconda3/envs/R_new/include -fdebug-prefix-map=/home/conda/feedstock_root/build_artifacts/r-base-split_1659993824316/work=/usr/local/src/conda/r-base-4.2.1 -fdebug-prefix-map=/home/jins/anaconda3/envs/R_new=/usr/local/src/conda-prefix  -c relative.c -o relative.o
x86_64-conda-linux-gnu-cc -I"/home/jins/anaconda3/envs/R_new/lib/R/include" -DNDEBUG   -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /home/jins/anaconda3/envs/R_new/include -I/home/jins/anaconda3/envs/R_new/include -Wl,-rpath-link,/home/jins/anaconda3/envs/R_new/lib   -fpic  -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/jins/anaconda3/envs/R_new/include -fdebug-prefix-map=/home/conda/feedstock_root/build_artifacts/r-base-split_1659993824316/work=/usr/local/src/conda/r-base-4.2.1 -fdebug-prefix-map=/home/jins/anaconda3/envs/R_new=/usr/local/src/conda-prefix  -c skater.c -o skater.o
x86_64-conda-linux-gnu-cc -I"/home/jins/anaconda3/envs/R_new/lib/R/include" -DNDEBUG   -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /home/jins/anaconda3/envs/R_new/include -I/home/jins/anaconda3/envs/R_new/include -Wl,-rpath-link,/home/jins/anaconda3/envs/R_new/lib   -fpic  -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/jins/anaconda3/envs/R_new/include -fdebug-prefix-map=/home/conda/feedstock_root/build_artifacts/r-base-split_1659993824316/work=/usr/local/src/conda/r-base-4.2.1 -fdebug-prefix-map=/home/jins/anaconda3/envs/R_new=/usr/local/src/conda-prefix  -c symtest.c -o symtest.o
x86_64-conda-linux-gnu-cc -shared -L/home/jins/anaconda3/envs/R_new/lib/R/lib -Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,--disable-new-dtags -Wl,--gc-sections -Wl,--allow-shlib-undefined -Wl,-rpath,/home/jins/anaconda3/envs/R_new/lib -Wl,-rpath-link,/home/jins/anaconda3/envs/R_new/lib -L/home/jins/anaconda3/envs/R_new/lib -o spdep.so card.o dfs_ncomp.o dnn.o gabriel.o gearyw.o gsymtest.o init.o insiders.o jc.o knn.o lagw.o listw2sn.o nbdists.o polypoly.o relative.o skater.o symtest.o -llapack -lblas -lgfortran -lm -lquadmath -L/home/jins/anaconda3/envs/R_new/lib/R/lib -lR
installing to /home/jins/anaconda3/envs/R_new/lib/R/library/00LOCK-spdep/00new/spdep/libs
** R
** data
** inst
** byte-compile and prepare package for lazy loading
double free or corruption (out)
Aborted (core dumped)
ERROR: lazy loading failed for package ‘spdep’
* removing ‘/home/jins/anaconda3/envs/R_new/lib/R/library/spdep’
Warning message:
In install.packages("/home/jins/spdep_1.2-6.tar.gz", repos = NULL,  :
  installation of package ‘/home/jins/spdep_1.2-6.tar.gz’ had non-zero exit status

Because I couldn't install spData or sf, sp via install.packages, so I turn to conda to help me build the r-spdata r-sf and r-sp.

**Comment by rsbivand** [comment]
If you use anaconda, no support caan be  given. Install sf, sp and spData simply, first installing sf's external dependencies https://github.com/r-spatial/sf/#ubuntu. Mixing compiler arguments is a clear potential cause of trouble.
